// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const defaultTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xffF3F3F3), color: Color(0xff444444)),
  'comment': TextStyle(color: Color(0xff697070)),
  'tag': TextStyle(color: Color(0xff444a)),
  'punctuation': TextStyle(color: Color(0xff444a)),
  'tag-name': TextStyle(color: Color(0xff444444)),
  'tag-attr': TextStyle(color: Color(0xff444444)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'attribute': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'meta-keyword': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'name': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xff880000)),
  'string': TextStyle(color: Color(0xff880000)),
  'number': TextStyle(color: Color(0xff880000)),
  'selector-id': TextStyle(color: Color(0xff880000)),
  'selector-class': TextStyle(color: Color(0xff880000)),
  'quote': TextStyle(color: Color(0xff880000)),
  'template-tag': TextStyle(color: Color(0xff880000)),
  'deletion': TextStyle(color: Color(0xff880000)),
  'title': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xff880000), fontWeight: FontWeight.bold),
  'regexp': TextStyle(color: Color(0xffab5656)),
  'symbol': TextStyle(color: Color(0xffab5656)),
  'variable': TextStyle(color: Color(0xffab5656)),
  'template-variable': TextStyle(color: Color(0xffab5656)),
  'link': TextStyle(color: Color(0xffab5656)),
  'selector-attr': TextStyle(color: Color(0xffab5656)),
  'operator': TextStyle(color: Color(0xffab5656)),
  'selector-pseudo': TextStyle(color: Color(0xffab5656)),
  'literal': TextStyle(color: Color(0xff669955)),
  'built_in': TextStyle(color: Color(0xff397300)),
  'bullet': TextStyle(color: Color(0xff397300)),
  'code': TextStyle(color: Color(0xff397300)),
  'addition': TextStyle(color: Color(0xff397300)),
  'meta': TextStyle(color: Color(0xff1f7199)),
  'meta-string': TextStyle(color: Color(0xff3388aa)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
