// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const devibeansTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff000000), color: Color(0xffa39e9b)),
  'attr': TextStyle(color: Color(0xff8787d7)),
  'template-tag': TextStyle(color: Color(0xff8787d7)),
  'comment': TextStyle(color: Color(0xff339966)),
  'doctag': TextStyle(color: Color(0xff339966)),
  'quote': TextStyle(color: Color(0xff339966)),
  'params': TextStyle(color: Color(0xffa39e9b)),
  'regexp': TextStyle(color: Color(0xffd700ff)),
  'tag': TextStyle(color: Color(0xffef5350)),
  'selector-id': TextStyle(color: Color(0xffef5350)),
  'number': TextStyle(color: Color(0xffef5350)),
  'literal': TextStyle(color: Color(0xffef5350)),
  'meta': TextStyle(color: Color(0xff0087ff)),
  'meta-keyword': TextStyle(color: Color(0xff0087ff)),
  'selector-class': TextStyle(color: Color(0xff64b5f6)),
  'code': TextStyle(color: Color(0xff64b5f6)),
  'formula': TextStyle(color: Color(0xff64b5f6)),
  'variable': TextStyle(color: Color(0xff64b5f6)),
  'template-variable': TextStyle(color: Color(0xff64b5f6)),
  'selector-attr': TextStyle(color: Color(0xff64b5f6)),
  'selector-pseudo': TextStyle(color: Color(0xff64b5f6)),
  'link': TextStyle(color: Color(0xff64b5f6)),
  'keyword': TextStyle(color: Color(0xff64b5f6)),
  'built_in': TextStyle(color: Color(0xffff8700)),
  'title': TextStyle(color: Color(0xffff8700)),
  'deletion': TextStyle(color: Color(0xffff8700)),
  'type': TextStyle(color: Color(0xffffd75f)),
  'section': TextStyle(color: Color(0xffffd75f)),
  'function': TextStyle(color: Color(0xffffd75f)),
  'name': TextStyle(color: Color(0xffffd75f)),
  'property': TextStyle(color: Color(0xffffd75f)),
  'attribute': TextStyle(color: Color(0xffffd75f)),
  'meta-string': TextStyle(color: Color(0xff558b2f)),
  'string': TextStyle(color: Color(0xff558b2f)),
  'subst': TextStyle(color: Color(0xff558b2f)),
  'symbol': TextStyle(color: Color(0xff558b2f)),
  'bullet': TextStyle(color: Color(0xff558b2f)),
  'addition': TextStyle(color: Color(0xff558b2f)),
  'selector-tag': TextStyle(color: Color(0xff9966ff)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
