// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const githubTheme = {
  'root':
      TextStyle(color: Color(0xff24292e), backgroundColor: Color(0xffffffff)),
  'doctag': TextStyle(color: Color(0xffd73a49)),
  'keyword': TextStyle(color: Color(0xffd73a49)),
  'meta-keyword': TextStyle(color: Color(0xffd73a49)),
  'template-tag': TextStyle(color: Color(0xffd73a49)),
  'template-variable': TextStyle(color: Color(0xffd73a49)),
  'type': TextStyle(color: Color(0xffd73a49)),
  'variable.language_': TextStyle(color: Color(0xffd73a49)),
  'title': TextStyle(color: Color(0xff6f42c1)),
  'title.class_': TextStyle(color: Color(0xff6f42c1)),
  'title.class_.inherited__': TextStyle(color: Color(0xff6f42c1)),
  'title.function_': TextStyle(color: Color(0xff6f42c1)),
  'attr': TextStyle(color: Color(0xff005cc5)),
  'attribute': TextStyle(color: Color(0xff005cc5)),
  'literal': TextStyle(color: Color(0xff005cc5)),
  'meta': TextStyle(color: Color(0xff005cc5)),
  'number': TextStyle(color: Color(0xff005cc5)),
  'operator': TextStyle(color: Color(0xff005cc5)),
  'variable': TextStyle(color: Color(0xff005cc5)),
  'selector-attr': TextStyle(color: Color(0xff005cc5)),
  'selector-class': TextStyle(color: Color(0xff005cc5)),
  'selector-id': TextStyle(color: Color(0xff005cc5)),
  'regexp': TextStyle(color: Color(0xff032f62)),
  'string': TextStyle(color: Color(0xff032f62)),
  'meta-string': TextStyle(color: Color(0xff032f62)),
  'built_in': TextStyle(color: Color(0xffe36209)),
  'symbol': TextStyle(color: Color(0xffe36209)),
  'comment': TextStyle(color: Color(0xff6a737d)),
  'code': TextStyle(color: Color(0xff6a737d)),
  'formula': TextStyle(color: Color(0xff6a737d)),
  'name': TextStyle(color: Color(0xff22863a)),
  'quote': TextStyle(color: Color(0xff22863a)),
  'selector-tag': TextStyle(color: Color(0xff22863a)),
  'selector-pseudo': TextStyle(color: Color(0xff22863a)),
  'subst': TextStyle(color: Color(0xff24292e)),
  'section': TextStyle(color: Color(0xff005cc5), fontWeight: FontWeight.bold),
  'bullet': TextStyle(color: Color(0xff735c0f)),
  'emphasis': TextStyle(color: Color(0xff24292e), fontStyle: FontStyle.italic),
  'strong': TextStyle(color: Color(0xff24292e), fontWeight: FontWeight.bold),
  'addition':
      TextStyle(color: Color(0xff22863a), backgroundColor: Color(0xfff0fff4)),
  'deletion':
      TextStyle(color: Color(0xffb31d28), backgroundColor: Color(0xffffeef0)),
};
