// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const githubDarkDimmedTheme = {
  'root':
      TextStyle(color: Color(0xffadbac7), backgroundColor: Color(0xff22272e)),
  'doctag': TextStyle(color: Color(0xfff47067)),
  'keyword': TextStyle(color: Color(0xfff47067)),
  'meta-keyword': TextStyle(color: Color(0xfff47067)),
  'template-tag': TextStyle(color: Color(0xfff47067)),
  'template-variable': TextStyle(color: Color(0xfff47067)),
  'type': TextStyle(color: Color(0xfff47067)),
  'variable.language_': TextStyle(color: Color(0xfff47067)),
  'title': TextStyle(color: Color(0xffdcbdfb)),
  'title.class_': TextStyle(color: Color(0xffdcbdfb)),
  'title.class_.inherited__': TextStyle(color: Color(0xffdcbdfb)),
  'title.function_': TextStyle(color: Color(0xffdcbdfb)),
  'attr': TextStyle(color: Color(0xff6cb6ff)),
  'attribute': TextStyle(color: Color(0xff6cb6ff)),
  'literal': TextStyle(color: Color(0xff6cb6ff)),
  'meta': TextStyle(color: Color(0xff6cb6ff)),
  'number': TextStyle(color: Color(0xff6cb6ff)),
  'operator': TextStyle(color: Color(0xff6cb6ff)),
  'variable': TextStyle(color: Color(0xff6cb6ff)),
  'selector-attr': TextStyle(color: Color(0xff6cb6ff)),
  'selector-class': TextStyle(color: Color(0xff6cb6ff)),
  'selector-id': TextStyle(color: Color(0xff6cb6ff)),
  'regexp': TextStyle(color: Color(0xff96d0ff)),
  'string': TextStyle(color: Color(0xff96d0ff)),
  'meta-string': TextStyle(color: Color(0xff96d0ff)),
  'built_in': TextStyle(color: Color(0xfff69d50)),
  'symbol': TextStyle(color: Color(0xfff69d50)),
  'comment': TextStyle(color: Color(0xff768390)),
  'code': TextStyle(color: Color(0xff768390)),
  'formula': TextStyle(color: Color(0xff768390)),
  'name': TextStyle(color: Color(0xff8ddb8c)),
  'quote': TextStyle(color: Color(0xff8ddb8c)),
  'selector-tag': TextStyle(color: Color(0xff8ddb8c)),
  'selector-pseudo': TextStyle(color: Color(0xff8ddb8c)),
  'subst': TextStyle(color: Color(0xffadbac7)),
  'section': TextStyle(color: Color(0xff316dca), fontWeight: FontWeight.bold),
  'bullet': TextStyle(color: Color(0xffeac55f)),
  'emphasis': TextStyle(color: Color(0xffadbac7), fontStyle: FontStyle.italic),
  'strong': TextStyle(color: Color(0xffadbac7), fontWeight: FontWeight.bold),
  'addition':
      TextStyle(color: Color(0xffb4f1b4), backgroundColor: Color(0xff1b4721)),
  'deletion':
      TextStyle(color: Color(0xffffd8d3), backgroundColor: Color(0xff78191b)),
};
