// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const githubDarkTheme = {
  'root':
      TextStyle(color: Color(0xffc9d1d9), backgroundColor: Color(0xff0d1117)),
  'doctag': TextStyle(color: Color(0xffff7b72)),
  'keyword': TextStyle(color: Color(0xffff7b72)),
  'meta-keyword': TextStyle(color: Color(0xffff7b72)),
  'template-tag': TextStyle(color: Color(0xffff7b72)),
  'template-variable': TextStyle(color: Color(0xffff7b72)),
  'type': TextStyle(color: Color(0xffff7b72)),
  'variable.language_': TextStyle(color: Color(0xffff7b72)),
  'title': TextStyle(color: Color(0xffd2a8ff)),
  'title.class_': TextStyle(color: Color(0xffd2a8ff)),
  'title.class_.inherited__': TextStyle(color: Color(0xffd2a8ff)),
  'title.function_': TextStyle(color: Color(0xffd2a8ff)),
  'attr': TextStyle(color: Color(0xff79c0ff)),
  'attribute': TextStyle(color: Color(0xff79c0ff)),
  'literal': TextStyle(color: Color(0xff79c0ff)),
  'meta': TextStyle(color: Color(0xff79c0ff)),
  'number': TextStyle(color: Color(0xff79c0ff)),
  'operator': TextStyle(color: Color(0xff79c0ff)),
  'variable': TextStyle(color: Color(0xff79c0ff)),
  'selector-attr': TextStyle(color: Color(0xff79c0ff)),
  'selector-class': TextStyle(color: Color(0xff79c0ff)),
  'selector-id': TextStyle(color: Color(0xff79c0ff)),
  'regexp': TextStyle(color: Color(0xffa5d6ff)),
  'string': TextStyle(color: Color(0xffa5d6ff)),
  'meta-string': TextStyle(color: Color(0xffa5d6ff)),
  'built_in': TextStyle(color: Color(0xffffa657)),
  'symbol': TextStyle(color: Color(0xffffa657)),
  'comment': TextStyle(color: Color(0xff8b949e)),
  'code': TextStyle(color: Color(0xff8b949e)),
  'formula': TextStyle(color: Color(0xff8b949e)),
  'name': TextStyle(color: Color(0xff7ee787)),
  'quote': TextStyle(color: Color(0xff7ee787)),
  'selector-tag': TextStyle(color: Color(0xff7ee787)),
  'selector-pseudo': TextStyle(color: Color(0xff7ee787)),
  'subst': TextStyle(color: Color(0xffc9d1d9)),
  'section': TextStyle(color: Color(0xff1f6feb), fontWeight: FontWeight.bold),
  'bullet': TextStyle(color: Color(0xfff2cc60)),
  'emphasis': TextStyle(color: Color(0xffc9d1d9), fontStyle: FontStyle.italic),
  'strong': TextStyle(color: Color(0xffc9d1d9), fontWeight: FontWeight.bold),
  'addition':
      TextStyle(color: Color(0xffaff5b4), backgroundColor: Color(0xff033a16)),
  'deletion':
      TextStyle(color: Color(0xffffdcd7), backgroundColor: Color(0xff67060c)),
};
