// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const intellijLightTheme = {
  'root':
      TextStyle(color: Color(0xff000000), backgroundColor: Color(0xffffffff)),
  'subst': TextStyle(color: Color(0xff000000)),
  'title': TextStyle(color: Color(0xff000000)),
  'title.function_': TextStyle(color: Color(0xff7A7A43)),
  'code': TextStyle(color: Color(0xff8C8C8C), fontStyle: FontStyle.italic),
  'comment': TextStyle(color: Color(0xff8C8C8C), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff8C8C8C), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff9E880D)),
  'section': TextStyle(color: Color(0xff871094)),
  'variable.language_': TextStyle(color: Color(0xff0033B3)),
  'symbol': TextStyle(color: Color(0xff0033B3)),
  'selector-class': TextStyle(color: Color(0xff0033B3)),
  'selector-id': TextStyle(color: Color(0xff0033B3)),
  'selector-tag': TextStyle(color: Color(0xff0033B3)),
  'template-tag': TextStyle(color: Color(0xff0033B3)),
  'selector-attr': TextStyle(color: Color(0xff0033B3)),
  'selector-pseudo': TextStyle(color: Color(0xff0033B3)),
  'keyword': TextStyle(color: Color(0xff0033B3)),
  'meta-keyword': TextStyle(color: Color(0xff0033B3)),
  'literal': TextStyle(color: Color(0xff0033B3)),
  'name': TextStyle(color: Color(0xff0033B3)),
  'built_in': TextStyle(color: Color(0xff0033B3)),
  'type': TextStyle(color: Color(0xff0033B3)),
  'property': TextStyle(color: Color(0xff871094)),
  'attr': TextStyle(color: Color(0xff871094)),
  'attribute': TextStyle(color: Color(0xff174AD4)),
  'number': TextStyle(color: Color(0xff1750EB)),
  'regexp': TextStyle(color: Color(0xff264EFF)),
  'link': TextStyle(color: Color(0xff006DCC)),
  'meta-string': TextStyle(color: Color(0xff067D17)),
  'string': TextStyle(color: Color(0xff067D17)),
  'char.escape_': TextStyle(color: Color(0xff0037A6)),
  'template-variable': TextStyle(color: Color(0xff248F8F)),
  'addition': TextStyle(backgroundColor: Color(0xffBEE6BE)),
  'deletion': TextStyle(backgroundColor: Color(0xffD6D6D6)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
