// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const nordTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff2E3440), color: Color(0xffD8DEE9)),
  'subst': TextStyle(color: Color(0xffD8DEE9)),
  'selector-tag': TextStyle(color: Color(0xff81A1C1)),
  'selector-id':
      TextStyle(color: Color(0xff8FBCBB), fontWeight: FontWeight.bold),
  'selector-class': TextStyle(color: Color(0xff8FBCBB)),
  'selector-attr': TextStyle(color: Color(0xff8FBCBB)),
  'property': TextStyle(color: Color(0xff88C0D0)),
  'selector-pseudo': TextStyle(color: Color(0xff88C0D0)),
  'addition': TextStyle(backgroundColor: Color.fromRGBO(163, 190, 140, 0.5)),
  'deletion': TextStyle(backgroundColor: Color.fromRGBO(191, 97, 106, 0.5)),
  'built_in': TextStyle(color: Color(0xff8FBCBB)),
  'type': TextStyle(color: Color(0xff8FBCBB)),
  'class': TextStyle(color: Color(0xff8FBCBB)),
  'function': TextStyle(color: Color(0xff88C0D0)),
  'title.hljs-function': TextStyle(color: Color(0xff88C0D0)),
  'function->-title': TextStyle(color: Color(0xff88C0D0)),
  'keyword': TextStyle(color: Color(0xff81A1C1)),
  'literal': TextStyle(color: Color(0xff81A1C1)),
  'symbol': TextStyle(color: Color(0xff81A1C1)),
  'number': TextStyle(color: Color(0xffB48EAD)),
  'regexp': TextStyle(color: Color(0xffEBCB8B)),
  'string': TextStyle(color: Color(0xffA3BE8C)),
  'title': TextStyle(color: Color(0xff8FBCBB)),
  'params': TextStyle(color: Color(0xffD8DEE9)),
  'bullet': TextStyle(color: Color(0xff81A1C1)),
  'code': TextStyle(color: Color(0xff8FBCBB)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'formula': TextStyle(color: Color(0xff8FBCBB)),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'quote': TextStyle(color: Color(0xff4C566A)),
  'comment': TextStyle(color: Color(0xff4C566A)),
  'doctag': TextStyle(color: Color(0xff8FBCBB)),
  'meta': TextStyle(color: Color(0xff5E81AC)),
  'meta-keyword': TextStyle(color: Color(0xff5E81AC)),
  'meta-string': TextStyle(color: Color(0xffA3BE8C)),
  'attr': TextStyle(color: Color(0xff8FBCBB)),
  'attribute': TextStyle(color: Color(0xffD8DEE9)),
  'name': TextStyle(color: Color(0xff81A1C1)),
  'section': TextStyle(color: Color(0xff88C0D0)),
  'tag': TextStyle(color: Color(0xff81A1C1)),
  'variable': TextStyle(color: Color(0xffD8DEE9)),
  'template-variable': TextStyle(color: Color(0xffD8DEE9)),
  'template-tag': TextStyle(color: Color(0xff5E81AC)),
  '.language-abnf-attribute': TextStyle(color: Color(0xff88C0D0)),
  '.language-abnf-symbol': TextStyle(color: Color(0xffEBCB8B)),
  '.language-apache-attribute': TextStyle(color: Color(0xff88C0D0)),
  '.language-apache-section': TextStyle(color: Color(0xff81A1C1)),
  '.language-arduino-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-aspectj-meta': TextStyle(color: Color(0xffD08770)),
  '.language-aspectj->-title': TextStyle(color: Color(0xff88C0D0)),
  '.language-bnf-attribute': TextStyle(color: Color(0xff8FBCBB)),
  '.language-clojure-name': TextStyle(color: Color(0xff88C0D0)),
  '.language-clojure-symbol': TextStyle(color: Color(0xffEBCB8B)),
  '.language-coq-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-cpp-meta-string': TextStyle(color: Color(0xff8FBCBB)),
  '.language-css-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-css-keyword': TextStyle(color: Color(0xffD08770)),
  '.language-diff-meta': TextStyle(color: Color(0xff8FBCBB)),
  '.language-ebnf-attribute': TextStyle(color: Color(0xff8FBCBB)),
  '.language-glsl-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-groovy-meta:not(:first-child)':
      TextStyle(color: Color(0xffD08770)),
  '.language-haxe-meta': TextStyle(color: Color(0xffD08770)),
  '.language-java-meta': TextStyle(color: Color(0xffD08770)),
  '.language-ldif-attribute': TextStyle(color: Color(0xff8FBCBB)),
  '.language-lisp-name': TextStyle(color: Color(0xff88C0D0)),
  '.language-lua-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-moonscript-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-nginx-attribute': TextStyle(color: Color(0xff88C0D0)),
  '.language-nginx-section': TextStyle(color: Color(0xff5E81AC)),
  '.language-pf-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-processing-built_in': TextStyle(color: Color(0xff88C0D0)),
  '.language-scss-keyword': TextStyle(color: Color(0xff81A1C1)),
  '.language-stylus-keyword': TextStyle(color: Color(0xff81A1C1)),
  '.language-swift-meta': TextStyle(color: Color(0xffD08770)),
  '.language-vim-built_in':
      TextStyle(color: Color(0xff88C0D0), fontStyle: FontStyle.italic),
  '.language-yaml-meta': TextStyle(color: Color(0xffD08770)),
};
