// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const pandaSyntaxDarkTheme = {
  'root':
      TextStyle(color: Color(0xffe6e6e6), backgroundColor: Color(0xff2a2c2d)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'comment': TextStyle(color: Color(0xffbbbbbb), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xffbbbbbb), fontStyle: FontStyle.italic),
  'params': TextStyle(color: Color(0xffbbbbbb)),
  'punctuation': TextStyle(color: Color(0xffffb86c)),
  'attr': TextStyle(color: Color(0xffe6e6e6)),
  'selector-tag': TextStyle(color: Color(0xffff4b82)),
  'name': TextStyle(color: Color(0xffff4b82)),
  'meta': TextStyle(color: Color(0xffff4b82)),
  'operator': TextStyle(color: Color(0xffb084eb)),
  'char.escape_': TextStyle(color: Color(0xffb084eb)),
  'keyword': TextStyle(color: Color(0xffff75b5)),
  'deletion': TextStyle(color: Color(0xffff75b5)),
  'regexp': TextStyle(color: Color(0xffff9ac1)),
  'selector-pseudo': TextStyle(color: Color(0xffff9ac1)),
  'selector-attr': TextStyle(color: Color(0xffff9ac1)),
  'variable.language_': TextStyle(color: Color(0xffff9ac1)),
  'subst': TextStyle(color: Color(0xff45a9f9)),
  'property': TextStyle(color: Color(0xff45a9f9)),
  'code': TextStyle(color: Color(0xff45a9f9)),
  'formula': TextStyle(color: Color(0xff45a9f9)),
  'section': TextStyle(color: Color(0xff45a9f9)),
  'title.function_': TextStyle(color: Color(0xff45a9f9)),
  'string': TextStyle(color: Color(0xff19f9d8)),
  'symbol': TextStyle(color: Color(0xff19f9d8)),
  'bullet': TextStyle(color: Color(0xff19f9d8)),
  'addition': TextStyle(color: Color(0xff19f9d8)),
  'selector-class': TextStyle(color: Color(0xff19f9d8)),
  'title.class_': TextStyle(color: Color(0xff19f9d8)),
  'title.class_.inherited__': TextStyle(color: Color(0xff19f9d8)),
  'meta-string': TextStyle(color: Color(0xff19f9d8)),
  'variable': TextStyle(color: Color(0xffffb86c)),
  'template-variable': TextStyle(color: Color(0xffffb86c)),
  'number': TextStyle(color: Color(0xffffb86c)),
  'literal': TextStyle(color: Color(0xffffb86c)),
  'type': TextStyle(color: Color(0xffffb86c)),
  'link': TextStyle(color: Color(0xffffb86c)),
  'built_in': TextStyle(color: Color(0xffffb86c)),
  'title': TextStyle(color: Color(0xffffb86c)),
  'selector-id': TextStyle(color: Color(0xffffb86c)),
  'tag': TextStyle(color: Color(0xffffb86c)),
  'doctag': TextStyle(color: Color(0xffffb86c)),
  'attribute': TextStyle(color: Color(0xffffb86c)),
  'template-tag': TextStyle(color: Color(0xffffb86c)),
  'meta-keyword': TextStyle(color: Color(0xffffb86c)),
};
