// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const pandaSyntaxLightTheme = {
  'root':
      TextStyle(color: Color(0xff2a2c2d), backgroundColor: Color(0xffe6e6e6)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'comment': TextStyle(color: Color(0xff676B79), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff676B79), fontStyle: FontStyle.italic),
  'params': TextStyle(color: Color(0xff676B79)),
  'punctuation': TextStyle(color: Color(0xff2a2c2d)),
  'attr': TextStyle(color: Color(0xff2a2c2d)),
  'selector-tag': TextStyle(color: Color(0xffc56200)),
  'name': TextStyle(color: Color(0xffc56200)),
  'meta': TextStyle(color: Color(0xffc56200)),
  'operator': TextStyle(color: Color(0xffc56200)),
  'char.escape_': TextStyle(color: Color(0xffc56200)),
  'keyword': TextStyle(color: Color(0xffd92792)),
  'deletion': TextStyle(color: Color(0xffd92792)),
  'regexp': TextStyle(color: Color(0xffcc5e91)),
  'selector-pseudo': TextStyle(color: Color(0xffcc5e91)),
  'selector-attr': TextStyle(color: Color(0xffcc5e91)),
  'variable.language_': TextStyle(color: Color(0xffcc5e91)),
  'subst': TextStyle(color: Color(0xff3787c7)),
  'property': TextStyle(color: Color(0xff3787c7)),
  'code': TextStyle(color: Color(0xff3787c7)),
  'formula': TextStyle(color: Color(0xff3787c7)),
  'section': TextStyle(color: Color(0xff3787c7)),
  'title.function_': TextStyle(color: Color(0xff3787c7)),
  'string': TextStyle(color: Color(0xff0d7d6c)),
  'symbol': TextStyle(color: Color(0xff0d7d6c)),
  'bullet': TextStyle(color: Color(0xff0d7d6c)),
  'addition': TextStyle(color: Color(0xff0d7d6c)),
  'selector-class': TextStyle(color: Color(0xff0d7d6c)),
  'title.class_': TextStyle(color: Color(0xff0d7d6c)),
  'title.class_.inherited__': TextStyle(color: Color(0xff0d7d6c)),
  'meta-string': TextStyle(color: Color(0xff0d7d6c)),
  'variable': TextStyle(color: Color(0xff7641bb)),
  'template-variable': TextStyle(color: Color(0xff7641bb)),
  'number': TextStyle(color: Color(0xff7641bb)),
  'literal': TextStyle(color: Color(0xff7641bb)),
  'type': TextStyle(color: Color(0xff7641bb)),
  'link': TextStyle(color: Color(0xff7641bb)),
  'built_in': TextStyle(color: Color(0xff7641bb)),
  'title': TextStyle(color: Color(0xff7641bb)),
  'selector-id': TextStyle(color: Color(0xff7641bb)),
  'tag': TextStyle(color: Color(0xff7641bb)),
  'doctag': TextStyle(color: Color(0xff7641bb)),
  'attribute': TextStyle(color: Color(0xff7641bb)),
  'template-tag': TextStyle(color: Color(0xff7641bb)),
  'meta-keyword': TextStyle(color: Color(0xff7641bb)),
};
