// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const stackoverflowDarkTheme = {
  'root':
      TextStyle(color: Color(0xffffffff), backgroundColor: Color(0xff1c1b1b)),
  'subst': TextStyle(color: Color(0xffffffff)),
  'comment': TextStyle(color: Color(0xff999999)),
  'keyword': TextStyle(color: Color(0xff88aece)),
  'selector-tag': TextStyle(color: Color(0xff88aece)),
  'meta-keyword': TextStyle(color: Color(0xff88aece)),
  'doctag': TextStyle(color: Color(0xff88aece)),
  'section': TextStyle(color: Color(0xff88aece)),
  'attr': TextStyle(color: Color(0xff88aece)),
  'attribute': TextStyle(color: Color(0xffc59bc1)),
  'name': TextStyle(color: Color(0xfff08d49)),
  'type': TextStyle(color: Color(0xfff08d49)),
  'number': TextStyle(color: Color(0xfff08d49)),
  'selector-id': TextStyle(color: Color(0xfff08d49)),
  'quote': TextStyle(color: Color(0xfff08d49)),
  'template-tag': TextStyle(color: Color(0xfff08d49)),
  'selector-class': TextStyle(color: Color(0xff88aece)),
  'string': TextStyle(color: Color(0xffb5bd68)),
  'regexp': TextStyle(color: Color(0xffb5bd68)),
  'symbol': TextStyle(color: Color(0xffb5bd68)),
  'variable': TextStyle(color: Color(0xffb5bd68)),
  'template-variable': TextStyle(color: Color(0xffb5bd68)),
  'link': TextStyle(color: Color(0xffb5bd68)),
  'selector-attr': TextStyle(color: Color(0xffb5bd68)),
  'meta': TextStyle(color: Color(0xff88aece)),
  'selector-pseudo': TextStyle(color: Color(0xff88aece)),
  'built_in': TextStyle(color: Color(0xfff08d49)),
  'title': TextStyle(color: Color(0xfff08d49)),
  'literal': TextStyle(color: Color(0xfff08d49)),
  'bullet': TextStyle(color: Color(0xffcccccc)),
  'code': TextStyle(color: Color(0xffcccccc)),
  'meta-string': TextStyle(color: Color(0xffb5bd68)),
  'deletion': TextStyle(color: Color(0xffde7176)),
  'addition': TextStyle(color: Color(0xff76c490)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
