// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const tokyoNightLightTheme = {
  'meta': TextStyle(color: Color(0xff9699a3)),
  'comment': TextStyle(color: Color(0xff9699a3)),
  'tag': TextStyle(color: Color(0xff8c4351)),
  'doctag': TextStyle(color: Color(0xff8c4351)),
  'selector-id': TextStyle(color: Color(0xff8c4351)),
  'selector-class': TextStyle(color: Color(0xff8c4351)),
  'regexp': TextStyle(color: Color(0xff8c4351)),
  'template-tag': TextStyle(color: Color(0xff8c4351)),
  'selector-pseudo': TextStyle(color: Color(0xff8c4351)),
  'selector-attr': TextStyle(color: Color(0xff8c4351)),
  'variable.language_': TextStyle(color: Color(0xff8c4351)),
  'deletion': TextStyle(color: Color(0xff8c4351)),
  'variable': TextStyle(color: Color(0xff965027)),
  'template-variable': TextStyle(color: Color(0xff965027)),
  'number': TextStyle(color: Color(0xff965027)),
  'literal': TextStyle(color: Color(0xff965027)),
  'type': TextStyle(color: Color(0xff965027)),
  'params': TextStyle(color: Color(0xff965027)),
  'link': TextStyle(color: Color(0xff965027)),
  'built_in': TextStyle(color: Color(0xff8f5e15)),
  'attribute': TextStyle(color: Color(0xff8f5e15)),
  'selector-tag': TextStyle(color: Color(0xff33635c)),
  'keyword': TextStyle(color: Color(0xff5a4a78)),
  'title.function_': TextStyle(color: Color(0xff0f4b6e)),
  'title': TextStyle(color: Color(0xff0f4b6e)),
  'title.class_': TextStyle(color: Color(0xff0f4b6e)),
  'title.class_.inherited__': TextStyle(color: Color(0xff0f4b6e)),
  'subst': TextStyle(color: Color(0xff0f4b6e)),
  'property': TextStyle(color: Color(0xff0f4b6e)),
  'quote': TextStyle(color: Color(0xff485e30)),
  'string': TextStyle(color: Color(0xff485e30)),
  'symbol': TextStyle(color: Color(0xff485e30)),
  'bullet': TextStyle(color: Color(0xff485e30)),
  'addition': TextStyle(color: Color(0xff485e30)),
  'code': TextStyle(color: Color(0xff34548a)),
  'formula': TextStyle(color: Color(0xff34548a)),
  'section': TextStyle(color: Color(0xff34548a)),
  'name': TextStyle(color: Color(0xff5a4a78)),
  'operator': TextStyle(color: Color(0xff5a4a78)),
  'char.escape_': TextStyle(color: Color(0xff5a4a78)),
  'attr': TextStyle(color: Color(0xff5a4a78)),
  'punctuation': TextStyle(color: Color(0xff343b58)),
  'root':
      TextStyle(backgroundColor: Color(0xffd5d6db), color: Color(0xff565a6e)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
