// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const atelierSeasideLightTheme = {
  'root':
      TextStyle(color: Color(0xff5e6e5e), backgroundColor: Color(0xfff4fbf4)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff8ca68c), color: Color(0xff5e6e5e)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff8ca68c), color: Color(0xff5e6e5e)),
  'comment': TextStyle(color: Color(0xff809980)),
  'tag': TextStyle(color: Color(0xff687d68)),
  'subst': TextStyle(color: Color(0xff5e6e5e)),
  'punctuation': TextStyle(color: Color(0xff5e6e5e)),
  'operator': TextStyle(color: Color(0xff5e6e5e)),
  'bullet': TextStyle(color: Color(0xffe6193c)),
  'variable': TextStyle(color: Color(0xffe6193c)),
  'template-variable': TextStyle(color: Color(0xffe6193c)),
  'selector-tag': TextStyle(color: Color(0xffe6193c)),
  'name': TextStyle(color: Color(0xffe6193c)),
  'deletion': TextStyle(color: Color(0xffe6193c)),
  'symbol': TextStyle(color: Color(0xff87711d)),
  'number': TextStyle(color: Color(0xff87711d)),
  'link': TextStyle(color: Color(0xff87711d)),
  'attr': TextStyle(color: Color(0xff87711d)),
  'variable.constant_': TextStyle(color: Color(0xff87711d)),
  'literal': TextStyle(color: Color(0xff87711d)),
  'title': TextStyle(color: Color(0xff98981b)),
  'class-title': TextStyle(color: Color(0xff98981b)),
  'title.class_': TextStyle(color: Color(0xff98981b)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff98981b)),
  'code': TextStyle(color: Color(0xff29a329)),
  'addition': TextStyle(color: Color(0xff29a329)),
  'title.class_.inherited__': TextStyle(color: Color(0xff29a329)),
  'string': TextStyle(color: Color(0xff29a329)),
  'built_in': TextStyle(color: Color(0xff1999b3)),
  'doctag': TextStyle(color: Color(0xff1999b3)),
  'quote': TextStyle(color: Color(0xff1999b3)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff1999b3)),
  'regexp': TextStyle(color: Color(0xff1999b3)),
  'function-title': TextStyle(color: Color(0xff3d62f5)),
  'attribute': TextStyle(color: Color(0xff3d62f5)),
  '.ruby-property': TextStyle(color: Color(0xff3d62f5)),
  'title.function_': TextStyle(color: Color(0xff3d62f5)),
  'section': TextStyle(color: Color(0xff3d62f5)),
  'type': TextStyle(color: Color(0xffad2bee)),
  'template-tag': TextStyle(color: Color(0xffad2bee)),
  '.diff-meta': TextStyle(color: Color(0xffad2bee)),
  'keyword': TextStyle(color: Color(0xffad2bee)),
  'emphasis': TextStyle(color: Color(0xffad2bee), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffe619c3)),
  'meta-keyword':
      TextStyle(color: Color(0xffe619c3), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffe619c3)),
};
