// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const atelierCaveTheme = {
  'root':
      TextStyle(color: Color(0xff8b8792), backgroundColor: Color(0xff19171c)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff585260), color: Color(0xff8b8792)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff585260), color: Color(0xff8b8792)),
  'comment': TextStyle(color: Color(0xff655f6d)),
  'tag': TextStyle(color: Color(0xff7e7887)),
  'subst': TextStyle(color: Color(0xff8b8792)),
  'punctuation': TextStyle(color: Color(0xff8b8792)),
  'operator': TextStyle(color: Color(0xff8b8792)),
  'bullet': TextStyle(color: Color(0xffbe4678)),
  'variable': TextStyle(color: Color(0xffbe4678)),
  'template-variable': TextStyle(color: Color(0xffbe4678)),
  'selector-tag': TextStyle(color: Color(0xffbe4678)),
  'name': TextStyle(color: Color(0xffbe4678)),
  'deletion': TextStyle(color: Color(0xffbe4678)),
  'symbol': TextStyle(color: Color(0xffaa573c)),
  'number': TextStyle(color: Color(0xffaa573c)),
  'link': TextStyle(color: Color(0xffaa573c)),
  'attr': TextStyle(color: Color(0xffaa573c)),
  'variable.constant_': TextStyle(color: Color(0xffaa573c)),
  'literal': TextStyle(color: Color(0xffaa573c)),
  'title': TextStyle(color: Color(0xffa06e3b)),
  'class-title': TextStyle(color: Color(0xffa06e3b)),
  'title.class_': TextStyle(color: Color(0xffa06e3b)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffa06e3b)),
  'code': TextStyle(color: Color(0xff2a9292)),
  'addition': TextStyle(color: Color(0xff2a9292)),
  'title.class_.inherited__': TextStyle(color: Color(0xff2a9292)),
  'string': TextStyle(color: Color(0xff2a9292)),
  'built_in': TextStyle(color: Color(0xff398bc6)),
  'doctag': TextStyle(color: Color(0xff398bc6)),
  'quote': TextStyle(color: Color(0xff398bc6)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff398bc6)),
  'regexp': TextStyle(color: Color(0xff398bc6)),
  'function-title': TextStyle(color: Color(0xff576ddb)),
  'attribute': TextStyle(color: Color(0xff576ddb)),
  '.ruby-property': TextStyle(color: Color(0xff576ddb)),
  'title.function_': TextStyle(color: Color(0xff576ddb)),
  'section': TextStyle(color: Color(0xff576ddb)),
  'type': TextStyle(color: Color(0xff955ae7)),
  'template-tag': TextStyle(color: Color(0xff955ae7)),
  '.diff-meta': TextStyle(color: Color(0xff955ae7)),
  'keyword': TextStyle(color: Color(0xff955ae7)),
  'emphasis': TextStyle(color: Color(0xff955ae7), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffbf40bf)),
  'meta-keyword':
      TextStyle(color: Color(0xffbf40bf), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffbf40bf)),
};
