// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const atelierHeathLightTheme = {
  'root':
      TextStyle(color: Color(0xff695d69), backgroundColor: Color(0xfff7f3f7)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xffab9bab), color: Color(0xff695d69)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xffab9bab), color: Color(0xff695d69)),
  'comment': TextStyle(color: Color(0xff9e8f9e)),
  'tag': TextStyle(color: Color(0xff776977)),
  'subst': TextStyle(color: Color(0xff695d69)),
  'punctuation': TextStyle(color: Color(0xff695d69)),
  'operator': TextStyle(color: Color(0xff695d69)),
  'bullet': TextStyle(color: Color(0xffca402b)),
  'variable': TextStyle(color: Color(0xffca402b)),
  'template-variable': TextStyle(color: Color(0xffca402b)),
  'selector-tag': TextStyle(color: Color(0xffca402b)),
  'name': TextStyle(color: Color(0xffca402b)),
  'deletion': TextStyle(color: Color(0xffca402b)),
  'symbol': TextStyle(color: Color(0xffa65926)),
  'number': TextStyle(color: Color(0xffa65926)),
  'link': TextStyle(color: Color(0xffa65926)),
  'attr': TextStyle(color: Color(0xffa65926)),
  'variable.constant_': TextStyle(color: Color(0xffa65926)),
  'literal': TextStyle(color: Color(0xffa65926)),
  'title': TextStyle(color: Color(0xffbb8a35)),
  'class-title': TextStyle(color: Color(0xffbb8a35)),
  'title.class_': TextStyle(color: Color(0xffbb8a35)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffbb8a35)),
  'code': TextStyle(color: Color(0xff918b3b)),
  'addition': TextStyle(color: Color(0xff918b3b)),
  'title.class_.inherited__': TextStyle(color: Color(0xff918b3b)),
  'string': TextStyle(color: Color(0xff918b3b)),
  'built_in': TextStyle(color: Color(0xff159393)),
  'doctag': TextStyle(color: Color(0xff159393)),
  'quote': TextStyle(color: Color(0xff159393)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff159393)),
  'regexp': TextStyle(color: Color(0xff159393)),
  'function-title': TextStyle(color: Color(0xff516aec)),
  'attribute': TextStyle(color: Color(0xff516aec)),
  '.ruby-property': TextStyle(color: Color(0xff516aec)),
  'title.function_': TextStyle(color: Color(0xff516aec)),
  'section': TextStyle(color: Color(0xff516aec)),
  'type': TextStyle(color: Color(0xff7b59c0)),
  'template-tag': TextStyle(color: Color(0xff7b59c0)),
  '.diff-meta': TextStyle(color: Color(0xff7b59c0)),
  'keyword': TextStyle(color: Color(0xff7b59c0)),
  'emphasis': TextStyle(color: Color(0xff7b59c0), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffcc33cc)),
  'meta-keyword':
      TextStyle(color: Color(0xffcc33cc), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffcc33cc)),
};
