// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const atelierEstuaryTheme = {
  'root':
      TextStyle(color: Color(0xff929181), backgroundColor: Color(0xff22221b)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff5f5e4e), color: Color(0xff929181)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff5f5e4e), color: Color(0xff929181)),
  'comment': TextStyle(color: Color(0xff6c6b5a)),
  'tag': TextStyle(color: Color(0xff878573)),
  'subst': TextStyle(color: Color(0xff929181)),
  'punctuation': TextStyle(color: Color(0xff929181)),
  'operator': TextStyle(color: Color(0xff929181)),
  'bullet': TextStyle(color: Color(0xffba6236)),
  'variable': TextStyle(color: Color(0xffba6236)),
  'template-variable': TextStyle(color: Color(0xffba6236)),
  'selector-tag': TextStyle(color: Color(0xffba6236)),
  'name': TextStyle(color: Color(0xffba6236)),
  'deletion': TextStyle(color: Color(0xffba6236)),
  'symbol': TextStyle(color: Color(0xffae7313)),
  'number': TextStyle(color: Color(0xffae7313)),
  'link': TextStyle(color: Color(0xffae7313)),
  'attr': TextStyle(color: Color(0xffae7313)),
  'variable.constant_': TextStyle(color: Color(0xffae7313)),
  'literal': TextStyle(color: Color(0xffae7313)),
  'title': TextStyle(color: Color(0xffa5980d)),
  'class-title': TextStyle(color: Color(0xffa5980d)),
  'title.class_': TextStyle(color: Color(0xffa5980d)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffa5980d)),
  'code': TextStyle(color: Color(0xff7d9726)),
  'addition': TextStyle(color: Color(0xff7d9726)),
  'title.class_.inherited__': TextStyle(color: Color(0xff7d9726)),
  'string': TextStyle(color: Color(0xff7d9726)),
  'built_in': TextStyle(color: Color(0xff5b9d48)),
  'doctag': TextStyle(color: Color(0xff5b9d48)),
  'quote': TextStyle(color: Color(0xff5b9d48)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff5b9d48)),
  'regexp': TextStyle(color: Color(0xff5b9d48)),
  'function-title': TextStyle(color: Color(0xff36a166)),
  'attribute': TextStyle(color: Color(0xff36a166)),
  '.ruby-property': TextStyle(color: Color(0xff36a166)),
  'title.function_': TextStyle(color: Color(0xff36a166)),
  'section': TextStyle(color: Color(0xff36a166)),
  'type': TextStyle(color: Color(0xff5f9182)),
  'template-tag': TextStyle(color: Color(0xff5f9182)),
  '.diff-meta': TextStyle(color: Color(0xff5f9182)),
  'keyword': TextStyle(color: Color(0xff5f9182)),
  'emphasis': TextStyle(color: Color(0xff5f9182), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff9d6c7c)),
  'meta-keyword':
      TextStyle(color: Color(0xff9d6c7c), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff9d6c7c)),
};
