// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const atelierPlateauTheme = {
  'root':
      TextStyle(color: Color(0xff8a8585), backgroundColor: Color(0xff1b1818)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff585050), color: Color(0xff8a8585)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff585050), color: Color(0xff8a8585)),
  'comment': TextStyle(color: Color(0xff655d5d)),
  'tag': TextStyle(color: Color(0xff7e7777)),
  'subst': TextStyle(color: Color(0xff8a8585)),
  'punctuation': TextStyle(color: Color(0xff8a8585)),
  'operator': TextStyle(color: Color(0xff8a8585)),
  'bullet': TextStyle(color: Color(0xffca4949)),
  'variable': TextStyle(color: Color(0xffca4949)),
  'template-variable': TextStyle(color: Color(0xffca4949)),
  'selector-tag': TextStyle(color: Color(0xffca4949)),
  'name': TextStyle(color: Color(0xffca4949)),
  'deletion': TextStyle(color: Color(0xffca4949)),
  'symbol': TextStyle(color: Color(0xffb45a3c)),
  'number': TextStyle(color: Color(0xffb45a3c)),
  'link': TextStyle(color: Color(0xffb45a3c)),
  'attr': TextStyle(color: Color(0xffb45a3c)),
  'variable.constant_': TextStyle(color: Color(0xffb45a3c)),
  'literal': TextStyle(color: Color(0xffb45a3c)),
  'title': TextStyle(color: Color(0xffa06e3b)),
  'class-title': TextStyle(color: Color(0xffa06e3b)),
  'title.class_': TextStyle(color: Color(0xffa06e3b)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffa06e3b)),
  'code': TextStyle(color: Color(0xff4b8b8b)),
  'addition': TextStyle(color: Color(0xff4b8b8b)),
  'title.class_.inherited__': TextStyle(color: Color(0xff4b8b8b)),
  'string': TextStyle(color: Color(0xff4b8b8b)),
  'built_in': TextStyle(color: Color(0xff5485b6)),
  'doctag': TextStyle(color: Color(0xff5485b6)),
  'quote': TextStyle(color: Color(0xff5485b6)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff5485b6)),
  'regexp': TextStyle(color: Color(0xff5485b6)),
  'function-title': TextStyle(color: Color(0xff7272ca)),
  'attribute': TextStyle(color: Color(0xff7272ca)),
  '.ruby-property': TextStyle(color: Color(0xff7272ca)),
  'title.function_': TextStyle(color: Color(0xff7272ca)),
  'section': TextStyle(color: Color(0xff7272ca)),
  'type': TextStyle(color: Color(0xff8464c4)),
  'template-tag': TextStyle(color: Color(0xff8464c4)),
  '.diff-meta': TextStyle(color: Color(0xff8464c4)),
  'keyword': TextStyle(color: Color(0xff8464c4)),
  'emphasis': TextStyle(color: Color(0xff8464c4), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffbd5187)),
  'meta-keyword':
      TextStyle(color: Color(0xffbd5187), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffbd5187)),
};
