// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const atelierSulphurpoolLightTheme = {
  'root':
      TextStyle(color: Color(0xff5e6687), backgroundColor: Color(0xfff5f7ff)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff979db4), color: Color(0xff5e6687)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff979db4), color: Color(0xff5e6687)),
  'comment': TextStyle(color: Color(0xff898ea4)),
  'tag': TextStyle(color: Color(0xff6b7394)),
  'subst': TextStyle(color: Color(0xff5e6687)),
  'punctuation': TextStyle(color: Color(0xff5e6687)),
  'operator': TextStyle(color: Color(0xff5e6687)),
  'bullet': TextStyle(color: Color(0xffc94922)),
  'variable': TextStyle(color: Color(0xffc94922)),
  'template-variable': TextStyle(color: Color(0xffc94922)),
  'selector-tag': TextStyle(color: Color(0xffc94922)),
  'name': TextStyle(color: Color(0xffc94922)),
  'deletion': TextStyle(color: Color(0xffc94922)),
  'symbol': TextStyle(color: Color(0xffc76b29)),
  'number': TextStyle(color: Color(0xffc76b29)),
  'link': TextStyle(color: Color(0xffc76b29)),
  'attr': TextStyle(color: Color(0xffc76b29)),
  'variable.constant_': TextStyle(color: Color(0xffc76b29)),
  'literal': TextStyle(color: Color(0xffc76b29)),
  'title': TextStyle(color: Color(0xffc08b30)),
  'class-title': TextStyle(color: Color(0xffc08b30)),
  'title.class_': TextStyle(color: Color(0xffc08b30)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffc08b30)),
  'code': TextStyle(color: Color(0xffac9739)),
  'addition': TextStyle(color: Color(0xffac9739)),
  'title.class_.inherited__': TextStyle(color: Color(0xffac9739)),
  'string': TextStyle(color: Color(0xffac9739)),
  'built_in': TextStyle(color: Color(0xff22a2c9)),
  'doctag': TextStyle(color: Color(0xff22a2c9)),
  'quote': TextStyle(color: Color(0xff22a2c9)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff22a2c9)),
  'regexp': TextStyle(color: Color(0xff22a2c9)),
  'function-title': TextStyle(color: Color(0xff3d8fd1)),
  'attribute': TextStyle(color: Color(0xff3d8fd1)),
  '.ruby-property': TextStyle(color: Color(0xff3d8fd1)),
  'title.function_': TextStyle(color: Color(0xff3d8fd1)),
  'section': TextStyle(color: Color(0xff3d8fd1)),
  'type': TextStyle(color: Color(0xff6679cc)),
  'template-tag': TextStyle(color: Color(0xff6679cc)),
  '.diff-meta': TextStyle(color: Color(0xff6679cc)),
  'keyword': TextStyle(color: Color(0xff6679cc)),
  'emphasis': TextStyle(color: Color(0xff6679cc), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff9c637a)),
  'meta-keyword':
      TextStyle(color: Color(0xff9c637a), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff9c637a)),
};
