// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const atlasTheme = {
  'root':
      TextStyle(color: Color(0xffa1a19a), backgroundColor: Color(0xff002635)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff517F8D), color: Color(0xffa1a19a)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff517F8D), color: Color(0xffa1a19a)),
  'comment': TextStyle(color: Color(0xff6C8B91)),
  'tag': TextStyle(color: Color(0xff869696)),
  'subst': TextStyle(color: Color(0xffa1a19a)),
  'punctuation': TextStyle(color: Color(0xffa1a19a)),
  'operator': TextStyle(color: Color(0xffa1a19a)),
  'bullet': TextStyle(color: Color(0xffff5a67)),
  'variable': TextStyle(color: Color(0xffff5a67)),
  'template-variable': TextStyle(color: Color(0xffff5a67)),
  'selector-tag': TextStyle(color: Color(0xffff5a67)),
  'name': TextStyle(color: Color(0xffff5a67)),
  'deletion': TextStyle(color: Color(0xffff5a67)),
  'symbol': TextStyle(color: Color(0xfff08e48)),
  'number': TextStyle(color: Color(0xfff08e48)),
  'link': TextStyle(color: Color(0xfff08e48)),
  'attr': TextStyle(color: Color(0xfff08e48)),
  'variable.constant_': TextStyle(color: Color(0xfff08e48)),
  'literal': TextStyle(color: Color(0xfff08e48)),
  'title': TextStyle(color: Color(0xffffcc1b)),
  'class-title': TextStyle(color: Color(0xffffcc1b)),
  'title.class_': TextStyle(color: Color(0xffffcc1b)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffffcc1b)),
  'code': TextStyle(color: Color(0xff7fc06e)),
  'addition': TextStyle(color: Color(0xff7fc06e)),
  'title.class_.inherited__': TextStyle(color: Color(0xff7fc06e)),
  'string': TextStyle(color: Color(0xff7fc06e)),
  'built_in': TextStyle(color: Color(0xff14747e)),
  'doctag': TextStyle(color: Color(0xff14747e)),
  'quote': TextStyle(color: Color(0xff14747e)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff14747e)),
  'regexp': TextStyle(color: Color(0xff14747e)),
  'function-title': TextStyle(color: Color(0xff5dd7b9)),
  'attribute': TextStyle(color: Color(0xff5dd7b9)),
  '.ruby-property': TextStyle(color: Color(0xff5dd7b9)),
  'title.function_': TextStyle(color: Color(0xff5dd7b9)),
  'section': TextStyle(color: Color(0xff5dd7b9)),
  'type': TextStyle(color: Color(0xff9a70a4)),
  'template-tag': TextStyle(color: Color(0xff9a70a4)),
  '.diff-meta': TextStyle(color: Color(0xff9a70a4)),
  'keyword': TextStyle(color: Color(0xff9a70a4)),
  'emphasis': TextStyle(color: Color(0xff9a70a4), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffc43060)),
  'meta-keyword':
      TextStyle(color: Color(0xffc43060), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffc43060)),
};
