// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const bespinTheme = {
  'root':
      TextStyle(color: Color(0xff8a8986), backgroundColor: Color(0xff28211c)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff5e5d5c), color: Color(0xff8a8986)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff5e5d5c), color: Color(0xff8a8986)),
  'comment': TextStyle(color: Color(0xff666666)),
  'tag': TextStyle(color: Color(0xff797977)),
  'subst': TextStyle(color: Color(0xff8a8986)),
  'punctuation': TextStyle(color: Color(0xff8a8986)),
  'operator': TextStyle(color: Color(0xff8a8986)),
  'bullet': TextStyle(color: Color(0xffcf6a4c)),
  'variable': TextStyle(color: Color(0xffcf6a4c)),
  'template-variable': TextStyle(color: Color(0xffcf6a4c)),
  'selector-tag': TextStyle(color: Color(0xffcf6a4c)),
  'name': TextStyle(color: Color(0xffcf6a4c)),
  'deletion': TextStyle(color: Color(0xffcf6a4c)),
  'symbol': TextStyle(color: Color(0xffcf7d34)),
  'number': TextStyle(color: Color(0xffcf7d34)),
  'link': TextStyle(color: Color(0xffcf7d34)),
  'attr': TextStyle(color: Color(0xffcf7d34)),
  'variable.constant_': TextStyle(color: Color(0xffcf7d34)),
  'literal': TextStyle(color: Color(0xffcf7d34)),
  'title': TextStyle(color: Color(0xfff9ee98)),
  'class-title': TextStyle(color: Color(0xfff9ee98)),
  'title.class_': TextStyle(color: Color(0xfff9ee98)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xfff9ee98)),
  'code': TextStyle(color: Color(0xff54be0d)),
  'addition': TextStyle(color: Color(0xff54be0d)),
  'title.class_.inherited__': TextStyle(color: Color(0xff54be0d)),
  'string': TextStyle(color: Color(0xff54be0d)),
  'built_in': TextStyle(color: Color(0xffafc4db)),
  'doctag': TextStyle(color: Color(0xffafc4db)),
  'quote': TextStyle(color: Color(0xffafc4db)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffafc4db)),
  'regexp': TextStyle(color: Color(0xffafc4db)),
  'function-title': TextStyle(color: Color(0xff5ea6ea)),
  'attribute': TextStyle(color: Color(0xff5ea6ea)),
  '.ruby-property': TextStyle(color: Color(0xff5ea6ea)),
  'title.function_': TextStyle(color: Color(0xff5ea6ea)),
  'section': TextStyle(color: Color(0xff5ea6ea)),
  'type': TextStyle(color: Color(0xff9b859d)),
  'template-tag': TextStyle(color: Color(0xff9b859d)),
  '.diff-meta': TextStyle(color: Color(0xff9b859d)),
  'keyword': TextStyle(color: Color(0xff9b859d)),
  'emphasis': TextStyle(color: Color(0xff9b859d), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff937121)),
  'meta-keyword':
      TextStyle(color: Color(0xff937121), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff937121)),
};
