// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const blackMetalNileTheme = {
  'root':
      TextStyle(color: Color(0xffc1c1c1), backgroundColor: Color(0xff000000)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff222222), color: Color(0xffc1c1c1)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff222222), color: Color(0xffc1c1c1)),
  'comment': TextStyle(color: Color(0xff333333)),
  'tag': TextStyle(color: Color(0xff999999)),
  'subst': TextStyle(color: Color(0xffc1c1c1)),
  'punctuation': TextStyle(color: Color(0xffc1c1c1)),
  'operator': TextStyle(color: Color(0xffc1c1c1)),
  'bullet': TextStyle(color: Color(0xff5f8787)),
  'variable': TextStyle(color: Color(0xff5f8787)),
  'template-variable': TextStyle(color: Color(0xff5f8787)),
  'selector-tag': TextStyle(color: Color(0xff5f8787)),
  'name': TextStyle(color: Color(0xff5f8787)),
  'deletion': TextStyle(color: Color(0xff5f8787)),
  'symbol': TextStyle(color: Color(0xffaaaaaa)),
  'number': TextStyle(color: Color(0xffaaaaaa)),
  'link': TextStyle(color: Color(0xffaaaaaa)),
  'attr': TextStyle(color: Color(0xffaaaaaa)),
  'variable.constant_': TextStyle(color: Color(0xffaaaaaa)),
  'literal': TextStyle(color: Color(0xffaaaaaa)),
  'title': TextStyle(color: Color(0xff777755)),
  'class-title': TextStyle(color: Color(0xff777755)),
  'title.class_': TextStyle(color: Color(0xff777755)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff777755)),
  'code': TextStyle(color: Color(0xffaa9988)),
  'addition': TextStyle(color: Color(0xffaa9988)),
  'title.class_.inherited__': TextStyle(color: Color(0xffaa9988)),
  'string': TextStyle(color: Color(0xffaa9988)),
  'built_in': TextStyle(color: Color(0xffaaaaaa)),
  'doctag': TextStyle(color: Color(0xffaaaaaa)),
  'quote': TextStyle(color: Color(0xffaaaaaa)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffaaaaaa)),
  'regexp': TextStyle(color: Color(0xffaaaaaa)),
  'function-title': TextStyle(color: Color(0xff888888)),
  'attribute': TextStyle(color: Color(0xff888888)),
  '.ruby-property': TextStyle(color: Color(0xff888888)),
  'title.function_': TextStyle(color: Color(0xff888888)),
  'section': TextStyle(color: Color(0xff888888)),
  'type': TextStyle(color: Color(0xff999999)),
  'template-tag': TextStyle(color: Color(0xff999999)),
  '.diff-meta': TextStyle(color: Color(0xff999999)),
  'keyword': TextStyle(color: Color(0xff999999)),
  'emphasis': TextStyle(color: Color(0xff999999), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff444444)),
  'meta-keyword':
      TextStyle(color: Color(0xff444444), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff444444)),
};
