// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const brewerTheme = {
  'root':
      TextStyle(color: Color(0xffb7b8b9), backgroundColor: Color(0xff0c0d0e)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff515253), color: Color(0xffb7b8b9)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff515253), color: Color(0xffb7b8b9)),
  'comment': TextStyle(color: Color(0xff737475)),
  'tag': TextStyle(color: Color(0xff959697)),
  'subst': TextStyle(color: Color(0xffb7b8b9)),
  'punctuation': TextStyle(color: Color(0xffb7b8b9)),
  'operator': TextStyle(color: Color(0xffb7b8b9)),
  'bullet': TextStyle(color: Color(0xffe31a1c)),
  'variable': TextStyle(color: Color(0xffe31a1c)),
  'template-variable': TextStyle(color: Color(0xffe31a1c)),
  'selector-tag': TextStyle(color: Color(0xffe31a1c)),
  'name': TextStyle(color: Color(0xffe31a1c)),
  'deletion': TextStyle(color: Color(0xffe31a1c)),
  'symbol': TextStyle(color: Color(0xffe6550d)),
  'number': TextStyle(color: Color(0xffe6550d)),
  'link': TextStyle(color: Color(0xffe6550d)),
  'attr': TextStyle(color: Color(0xffe6550d)),
  'variable.constant_': TextStyle(color: Color(0xffe6550d)),
  'literal': TextStyle(color: Color(0xffe6550d)),
  'title': TextStyle(color: Color(0xffdca060)),
  'class-title': TextStyle(color: Color(0xffdca060)),
  'title.class_': TextStyle(color: Color(0xffdca060)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffdca060)),
  'code': TextStyle(color: Color(0xff31a354)),
  'addition': TextStyle(color: Color(0xff31a354)),
  'title.class_.inherited__': TextStyle(color: Color(0xff31a354)),
  'string': TextStyle(color: Color(0xff31a354)),
  'built_in': TextStyle(color: Color(0xff80b1d3)),
  'doctag': TextStyle(color: Color(0xff80b1d3)),
  'quote': TextStyle(color: Color(0xff80b1d3)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff80b1d3)),
  'regexp': TextStyle(color: Color(0xff80b1d3)),
  'function-title': TextStyle(color: Color(0xff3182bd)),
  'attribute': TextStyle(color: Color(0xff3182bd)),
  '.ruby-property': TextStyle(color: Color(0xff3182bd)),
  'title.function_': TextStyle(color: Color(0xff3182bd)),
  'section': TextStyle(color: Color(0xff3182bd)),
  'type': TextStyle(color: Color(0xff756bb1)),
  'template-tag': TextStyle(color: Color(0xff756bb1)),
  '.diff-meta': TextStyle(color: Color(0xff756bb1)),
  'keyword': TextStyle(color: Color(0xff756bb1)),
  'emphasis': TextStyle(color: Color(0xff756bb1), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffb15928)),
  'meta-keyword':
      TextStyle(color: Color(0xffb15928), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffb15928)),
};
