// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const brightTheme = {
  'root':
      TextStyle(color: Color(0xffe0e0e0), backgroundColor: Color(0xff000000)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff505050), color: Color(0xffe0e0e0)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff505050), color: Color(0xffe0e0e0)),
  'comment': TextStyle(color: Color(0xffb0b0b0)),
  'tag': TextStyle(color: Color(0xffd0d0d0)),
  'subst': TextStyle(color: Color(0xffe0e0e0)),
  'punctuation': TextStyle(color: Color(0xffe0e0e0)),
  'operator': TextStyle(color: Color(0xffe0e0e0)),
  'bullet': TextStyle(color: Color(0xfffb0120)),
  'variable': TextStyle(color: Color(0xfffb0120)),
  'template-variable': TextStyle(color: Color(0xfffb0120)),
  'selector-tag': TextStyle(color: Color(0xfffb0120)),
  'name': TextStyle(color: Color(0xfffb0120)),
  'deletion': TextStyle(color: Color(0xfffb0120)),
  'symbol': TextStyle(color: Color(0xfffc6d24)),
  'number': TextStyle(color: Color(0xfffc6d24)),
  'link': TextStyle(color: Color(0xfffc6d24)),
  'attr': TextStyle(color: Color(0xfffc6d24)),
  'variable.constant_': TextStyle(color: Color(0xfffc6d24)),
  'literal': TextStyle(color: Color(0xfffc6d24)),
  'title': TextStyle(color: Color(0xfffda331)),
  'class-title': TextStyle(color: Color(0xfffda331)),
  'title.class_': TextStyle(color: Color(0xfffda331)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xfffda331)),
  'code': TextStyle(color: Color(0xffa1c659)),
  'addition': TextStyle(color: Color(0xffa1c659)),
  'title.class_.inherited__': TextStyle(color: Color(0xffa1c659)),
  'string': TextStyle(color: Color(0xffa1c659)),
  'built_in': TextStyle(color: Color(0xff76c7b7)),
  'doctag': TextStyle(color: Color(0xff76c7b7)),
  'quote': TextStyle(color: Color(0xff76c7b7)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff76c7b7)),
  'regexp': TextStyle(color: Color(0xff76c7b7)),
  'function-title': TextStyle(color: Color(0xff6fb3d2)),
  'attribute': TextStyle(color: Color(0xff6fb3d2)),
  '.ruby-property': TextStyle(color: Color(0xff6fb3d2)),
  'title.function_': TextStyle(color: Color(0xff6fb3d2)),
  'section': TextStyle(color: Color(0xff6fb3d2)),
  'type': TextStyle(color: Color(0xffd381c3)),
  'template-tag': TextStyle(color: Color(0xffd381c3)),
  '.diff-meta': TextStyle(color: Color(0xffd381c3)),
  'keyword': TextStyle(color: Color(0xffd381c3)),
  'emphasis': TextStyle(color: Color(0xffd381c3), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffbe643c)),
  'meta-keyword':
      TextStyle(color: Color(0xffbe643c), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffbe643c)),
};
