// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const brushTreesTheme = {
  'root':
      TextStyle(color: Color(0xff6D828E), backgroundColor: Color(0xffE3EFEF)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xffB0C5C8), color: Color(0xff6D828E)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xffB0C5C8), color: Color(0xff6D828E)),
  'comment': TextStyle(color: Color(0xff98AFB5)),
  'tag': TextStyle(color: Color(0xff8299A1)),
  'subst': TextStyle(color: Color(0xff6D828E)),
  'punctuation': TextStyle(color: Color(0xff6D828E)),
  'operator': TextStyle(color: Color(0xff6D828E)),
  'bullet': TextStyle(color: Color(0xffb38686)),
  'variable': TextStyle(color: Color(0xffb38686)),
  'template-variable': TextStyle(color: Color(0xffb38686)),
  'selector-tag': TextStyle(color: Color(0xffb38686)),
  'name': TextStyle(color: Color(0xffb38686)),
  'deletion': TextStyle(color: Color(0xffb38686)),
  'symbol': TextStyle(color: Color(0xffd8bba2)),
  'number': TextStyle(color: Color(0xffd8bba2)),
  'link': TextStyle(color: Color(0xffd8bba2)),
  'attr': TextStyle(color: Color(0xffd8bba2)),
  'variable.constant_': TextStyle(color: Color(0xffd8bba2)),
  'literal': TextStyle(color: Color(0xffd8bba2)),
  'title': TextStyle(color: Color(0xffaab386)),
  'class-title': TextStyle(color: Color(0xffaab386)),
  'title.class_': TextStyle(color: Color(0xffaab386)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffaab386)),
  'code': TextStyle(color: Color(0xff87b386)),
  'addition': TextStyle(color: Color(0xff87b386)),
  'title.class_.inherited__': TextStyle(color: Color(0xff87b386)),
  'string': TextStyle(color: Color(0xff87b386)),
  'built_in': TextStyle(color: Color(0xff86b3b3)),
  'doctag': TextStyle(color: Color(0xff86b3b3)),
  'quote': TextStyle(color: Color(0xff86b3b3)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff86b3b3)),
  'regexp': TextStyle(color: Color(0xff86b3b3)),
  'function-title': TextStyle(color: Color(0xff868cb3)),
  'attribute': TextStyle(color: Color(0xff868cb3)),
  '.ruby-property': TextStyle(color: Color(0xff868cb3)),
  'title.function_': TextStyle(color: Color(0xff868cb3)),
  'section': TextStyle(color: Color(0xff868cb3)),
  'type': TextStyle(color: Color(0xffb386b2)),
  'template-tag': TextStyle(color: Color(0xffb386b2)),
  '.diff-meta': TextStyle(color: Color(0xffb386b2)),
  'keyword': TextStyle(color: Color(0xffb386b2)),
  'emphasis': TextStyle(color: Color(0xffb386b2), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffb39f9f)),
  'meta-keyword':
      TextStyle(color: Color(0xffb39f9f), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffb39f9f)),
};
