// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const classicDarkTheme = {
  'root':
      TextStyle(color: Color(0xffD0D0D0), backgroundColor: Color(0xff151515)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff303030), color: Color(0xffD0D0D0)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff303030), color: Color(0xffD0D0D0)),
  'comment': TextStyle(color: Color(0xff505050)),
  'tag': TextStyle(color: Color(0xffB0B0B0)),
  'subst': TextStyle(color: Color(0xffD0D0D0)),
  'punctuation': TextStyle(color: Color(0xffD0D0D0)),
  'operator': TextStyle(color: Color(0xffD0D0D0)),
  'bullet': TextStyle(color: Color(0xffAC4142)),
  'variable': TextStyle(color: Color(0xffAC4142)),
  'template-variable': TextStyle(color: Color(0xffAC4142)),
  'selector-tag': TextStyle(color: Color(0xffAC4142)),
  'name': TextStyle(color: Color(0xffAC4142)),
  'deletion': TextStyle(color: Color(0xffAC4142)),
  'symbol': TextStyle(color: Color(0xffD28445)),
  'number': TextStyle(color: Color(0xffD28445)),
  'link': TextStyle(color: Color(0xffD28445)),
  'attr': TextStyle(color: Color(0xffD28445)),
  'variable.constant_': TextStyle(color: Color(0xffD28445)),
  'literal': TextStyle(color: Color(0xffD28445)),
  'title': TextStyle(color: Color(0xffF4BF75)),
  'class-title': TextStyle(color: Color(0xffF4BF75)),
  'title.class_': TextStyle(color: Color(0xffF4BF75)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffF4BF75)),
  'code': TextStyle(color: Color(0xff90A959)),
  'addition': TextStyle(color: Color(0xff90A959)),
  'title.class_.inherited__': TextStyle(color: Color(0xff90A959)),
  'string': TextStyle(color: Color(0xff90A959)),
  'built_in': TextStyle(color: Color(0xff75B5AA)),
  'doctag': TextStyle(color: Color(0xff75B5AA)),
  'quote': TextStyle(color: Color(0xff75B5AA)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff75B5AA)),
  'regexp': TextStyle(color: Color(0xff75B5AA)),
  'function-title': TextStyle(color: Color(0xff6A9FB5)),
  'attribute': TextStyle(color: Color(0xff6A9FB5)),
  '.ruby-property': TextStyle(color: Color(0xff6A9FB5)),
  'title.function_': TextStyle(color: Color(0xff6A9FB5)),
  'section': TextStyle(color: Color(0xff6A9FB5)),
  'type': TextStyle(color: Color(0xffAA759F)),
  'template-tag': TextStyle(color: Color(0xffAA759F)),
  '.diff-meta': TextStyle(color: Color(0xffAA759F)),
  'keyword': TextStyle(color: Color(0xffAA759F)),
  'emphasis': TextStyle(color: Color(0xffAA759F), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff8F5536)),
  'meta-keyword':
      TextStyle(color: Color(0xff8F5536), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff8F5536)),
};
