// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const codeschoolTheme = {
  'root':
      TextStyle(color: Color(0xff9ea7a6), backgroundColor: Color(0xff232c31)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff2a343a), color: Color(0xff9ea7a6)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff2a343a), color: Color(0xff9ea7a6)),
  'comment': TextStyle(color: Color(0xff3f4944)),
  'tag': TextStyle(color: Color(0xff84898c)),
  'subst': TextStyle(color: Color(0xff9ea7a6)),
  'punctuation': TextStyle(color: Color(0xff9ea7a6)),
  'operator': TextStyle(color: Color(0xff9ea7a6)),
  'bullet': TextStyle(color: Color(0xff2a5491)),
  'variable': TextStyle(color: Color(0xff2a5491)),
  'template-variable': TextStyle(color: Color(0xff2a5491)),
  'selector-tag': TextStyle(color: Color(0xff2a5491)),
  'name': TextStyle(color: Color(0xff2a5491)),
  'deletion': TextStyle(color: Color(0xff2a5491)),
  'symbol': TextStyle(color: Color(0xff43820d)),
  'number': TextStyle(color: Color(0xff43820d)),
  'link': TextStyle(color: Color(0xff43820d)),
  'attr': TextStyle(color: Color(0xff43820d)),
  'variable.constant_': TextStyle(color: Color(0xff43820d)),
  'literal': TextStyle(color: Color(0xff43820d)),
  'title': TextStyle(color: Color(0xffa03b1e)),
  'class-title': TextStyle(color: Color(0xffa03b1e)),
  'title.class_': TextStyle(color: Color(0xffa03b1e)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffa03b1e)),
  'code': TextStyle(color: Color(0xff237986)),
  'addition': TextStyle(color: Color(0xff237986)),
  'title.class_.inherited__': TextStyle(color: Color(0xff237986)),
  'string': TextStyle(color: Color(0xff237986)),
  'built_in': TextStyle(color: Color(0xffb02f30)),
  'doctag': TextStyle(color: Color(0xffb02f30)),
  'quote': TextStyle(color: Color(0xffb02f30)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffb02f30)),
  'regexp': TextStyle(color: Color(0xffb02f30)),
  'function-title': TextStyle(color: Color(0xff484d79)),
  'attribute': TextStyle(color: Color(0xff484d79)),
  '.ruby-property': TextStyle(color: Color(0xff484d79)),
  'title.function_': TextStyle(color: Color(0xff484d79)),
  'section': TextStyle(color: Color(0xff484d79)),
  'type': TextStyle(color: Color(0xffc59820)),
  'template-tag': TextStyle(color: Color(0xffc59820)),
  '.diff-meta': TextStyle(color: Color(0xffc59820)),
  'keyword': TextStyle(color: Color(0xffc59820)),
  'emphasis': TextStyle(color: Color(0xffc59820), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffc98344)),
  'meta-keyword':
      TextStyle(color: Color(0xffc98344), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffc98344)),
};
