// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const draculaTheme = {
  'root':
      TextStyle(color: Color(0xffe9e9f4), backgroundColor: Color(0xff282936)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff4d4f68), color: Color(0xffe9e9f4)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff4d4f68), color: Color(0xffe9e9f4)),
  'comment': TextStyle(color: Color(0xff626483)),
  'tag': TextStyle(color: Color(0xff62d6e8)),
  'subst': TextStyle(color: Color(0xffe9e9f4)),
  'punctuation': TextStyle(color: Color(0xffe9e9f4)),
  'operator': TextStyle(color: Color(0xffe9e9f4)),
  'bullet': TextStyle(color: Color(0xffea51b2)),
  'variable': TextStyle(color: Color(0xffea51b2)),
  'template-variable': TextStyle(color: Color(0xffea51b2)),
  'selector-tag': TextStyle(color: Color(0xffea51b2)),
  'name': TextStyle(color: Color(0xffea51b2)),
  'deletion': TextStyle(color: Color(0xffea51b2)),
  'symbol': TextStyle(color: Color(0xffb45bcf)),
  'number': TextStyle(color: Color(0xffb45bcf)),
  'link': TextStyle(color: Color(0xffb45bcf)),
  'attr': TextStyle(color: Color(0xffb45bcf)),
  'variable.constant_': TextStyle(color: Color(0xffb45bcf)),
  'literal': TextStyle(color: Color(0xffb45bcf)),
  'title': TextStyle(color: Color(0xff00f769)),
  'class-title': TextStyle(color: Color(0xff00f769)),
  'title.class_': TextStyle(color: Color(0xff00f769)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff00f769)),
  'code': TextStyle(color: Color(0xffebff87)),
  'addition': TextStyle(color: Color(0xffebff87)),
  'title.class_.inherited__': TextStyle(color: Color(0xffebff87)),
  'string': TextStyle(color: Color(0xffebff87)),
  'built_in': TextStyle(color: Color(0xffa1efe4)),
  'doctag': TextStyle(color: Color(0xffa1efe4)),
  'quote': TextStyle(color: Color(0xffa1efe4)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffa1efe4)),
  'regexp': TextStyle(color: Color(0xffa1efe4)),
  'function-title': TextStyle(color: Color(0xff62d6e8)),
  'attribute': TextStyle(color: Color(0xff62d6e8)),
  '.ruby-property': TextStyle(color: Color(0xff62d6e8)),
  'title.function_': TextStyle(color: Color(0xff62d6e8)),
  'section': TextStyle(color: Color(0xff62d6e8)),
  'type': TextStyle(color: Color(0xffb45bcf)),
  'template-tag': TextStyle(color: Color(0xffb45bcf)),
  '.diff-meta': TextStyle(color: Color(0xffb45bcf)),
  'keyword': TextStyle(color: Color(0xffb45bcf)),
  'emphasis': TextStyle(color: Color(0xffb45bcf), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff00f769)),
  'meta-keyword':
      TextStyle(color: Color(0xff00f769), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff00f769)),
};
