// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const edgeDarkTheme = {
  'root':
      TextStyle(color: Color(0xffb7bec9), backgroundColor: Color(0xff262729)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xffb7bec9), color: Color(0xffb7bec9)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xffb7bec9), color: Color(0xffb7bec9)),
  'comment': TextStyle(color: Color(0xff3e4249)),
  'tag': TextStyle(color: Color(0xff73b3e7)),
  'subst': TextStyle(color: Color(0xffb7bec9)),
  'punctuation': TextStyle(color: Color(0xffb7bec9)),
  'operator': TextStyle(color: Color(0xffb7bec9)),
  'bullet': TextStyle(color: Color(0xffe77171)),
  'variable': TextStyle(color: Color(0xffe77171)),
  'template-variable': TextStyle(color: Color(0xffe77171)),
  'selector-tag': TextStyle(color: Color(0xffe77171)),
  'name': TextStyle(color: Color(0xffe77171)),
  'deletion': TextStyle(color: Color(0xffe77171)),
  'symbol': TextStyle(color: Color(0xffe77171)),
  'number': TextStyle(color: Color(0xffe77171)),
  'link': TextStyle(color: Color(0xffe77171)),
  'attr': TextStyle(color: Color(0xffe77171)),
  'variable.constant_': TextStyle(color: Color(0xffe77171)),
  'literal': TextStyle(color: Color(0xffe77171)),
  'title': TextStyle(color: Color(0xffdbb774)),
  'class-title': TextStyle(color: Color(0xffdbb774)),
  'title.class_': TextStyle(color: Color(0xffdbb774)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffdbb774)),
  'code': TextStyle(color: Color(0xffa1bf78)),
  'addition': TextStyle(color: Color(0xffa1bf78)),
  'title.class_.inherited__': TextStyle(color: Color(0xffa1bf78)),
  'string': TextStyle(color: Color(0xffa1bf78)),
  'built_in': TextStyle(color: Color(0xff5ebaa5)),
  'doctag': TextStyle(color: Color(0xff5ebaa5)),
  'quote': TextStyle(color: Color(0xff5ebaa5)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff5ebaa5)),
  'regexp': TextStyle(color: Color(0xff5ebaa5)),
  'function-title': TextStyle(color: Color(0xff73b3e7)),
  'attribute': TextStyle(color: Color(0xff73b3e7)),
  '.ruby-property': TextStyle(color: Color(0xff73b3e7)),
  'title.function_': TextStyle(color: Color(0xff73b3e7)),
  'section': TextStyle(color: Color(0xff73b3e7)),
  'type': TextStyle(color: Color(0xffd390e7)),
  'template-tag': TextStyle(color: Color(0xffd390e7)),
  '.diff-meta': TextStyle(color: Color(0xffd390e7)),
  'keyword': TextStyle(color: Color(0xffd390e7)),
  'emphasis': TextStyle(color: Color(0xffd390e7), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff5ebaa5)),
  'meta-keyword':
      TextStyle(color: Color(0xff5ebaa5), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff5ebaa5)),
};
