// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const framerTheme = {
  'root':
      TextStyle(color: Color(0xffD0D0D0), backgroundColor: Color(0xff181818)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff464646), color: Color(0xffD0D0D0)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff464646), color: Color(0xffD0D0D0)),
  'comment': TextStyle(color: Color(0xff747474)),
  'tag': TextStyle(color: Color(0xffB9B9B9)),
  'subst': TextStyle(color: Color(0xffD0D0D0)),
  'punctuation': TextStyle(color: Color(0xffD0D0D0)),
  'operator': TextStyle(color: Color(0xffD0D0D0)),
  'bullet': TextStyle(color: Color(0xffFD886B)),
  'variable': TextStyle(color: Color(0xffFD886B)),
  'template-variable': TextStyle(color: Color(0xffFD886B)),
  'selector-tag': TextStyle(color: Color(0xffFD886B)),
  'name': TextStyle(color: Color(0xffFD886B)),
  'deletion': TextStyle(color: Color(0xffFD886B)),
  'symbol': TextStyle(color: Color(0xffFC4769)),
  'number': TextStyle(color: Color(0xffFC4769)),
  'link': TextStyle(color: Color(0xffFC4769)),
  'attr': TextStyle(color: Color(0xffFC4769)),
  'variable.constant_': TextStyle(color: Color(0xffFC4769)),
  'literal': TextStyle(color: Color(0xffFC4769)),
  'title': TextStyle(color: Color(0xffFECB6E)),
  'class-title': TextStyle(color: Color(0xffFECB6E)),
  'title.class_': TextStyle(color: Color(0xffFECB6E)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffFECB6E)),
  'code': TextStyle(color: Color(0xff32CCDC)),
  'addition': TextStyle(color: Color(0xff32CCDC)),
  'title.class_.inherited__': TextStyle(color: Color(0xff32CCDC)),
  'string': TextStyle(color: Color(0xff32CCDC)),
  'built_in': TextStyle(color: Color(0xffACDDFD)),
  'doctag': TextStyle(color: Color(0xffACDDFD)),
  'quote': TextStyle(color: Color(0xffACDDFD)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffACDDFD)),
  'regexp': TextStyle(color: Color(0xffACDDFD)),
  'function-title': TextStyle(color: Color(0xff20BCFC)),
  'attribute': TextStyle(color: Color(0xff20BCFC)),
  '.ruby-property': TextStyle(color: Color(0xff20BCFC)),
  'title.function_': TextStyle(color: Color(0xff20BCFC)),
  'section': TextStyle(color: Color(0xff20BCFC)),
  'type': TextStyle(color: Color(0xffBA8CFC)),
  'template-tag': TextStyle(color: Color(0xffBA8CFC)),
  '.diff-meta': TextStyle(color: Color(0xffBA8CFC)),
  'keyword': TextStyle(color: Color(0xffBA8CFC)),
  'emphasis': TextStyle(color: Color(0xffBA8CFC), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffB15F4A)),
  'meta-keyword':
      TextStyle(color: Color(0xffB15F4A), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffB15F4A)),
};
