// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const gigavoltTheme = {
  'root':
      TextStyle(color: Color(0xffe9e7e1), backgroundColor: Color(0xff202126)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff5a576e), color: Color(0xffe9e7e1)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff5a576e), color: Color(0xffe9e7e1)),
  'comment': TextStyle(color: Color(0xffa1d2e6)),
  'tag': TextStyle(color: Color(0xffcad3ff)),
  'subst': TextStyle(color: Color(0xffe9e7e1)),
  'punctuation': TextStyle(color: Color(0xffe9e7e1)),
  'operator': TextStyle(color: Color(0xffe9e7e1)),
  'bullet': TextStyle(color: Color(0xffff661a)),
  'variable': TextStyle(color: Color(0xffff661a)),
  'template-variable': TextStyle(color: Color(0xffff661a)),
  'selector-tag': TextStyle(color: Color(0xffff661a)),
  'name': TextStyle(color: Color(0xffff661a)),
  'deletion': TextStyle(color: Color(0xffff661a)),
  'symbol': TextStyle(color: Color(0xff19f988)),
  'number': TextStyle(color: Color(0xff19f988)),
  'link': TextStyle(color: Color(0xff19f988)),
  'attr': TextStyle(color: Color(0xff19f988)),
  'variable.constant_': TextStyle(color: Color(0xff19f988)),
  'literal': TextStyle(color: Color(0xff19f988)),
  'title': TextStyle(color: Color(0xffffdc2d)),
  'class-title': TextStyle(color: Color(0xffffdc2d)),
  'title.class_': TextStyle(color: Color(0xffffdc2d)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffffdc2d)),
  'code': TextStyle(color: Color(0xfff2e6a9)),
  'addition': TextStyle(color: Color(0xfff2e6a9)),
  'title.class_.inherited__': TextStyle(color: Color(0xfff2e6a9)),
  'string': TextStyle(color: Color(0xfff2e6a9)),
  'built_in': TextStyle(color: Color(0xfffb6acb)),
  'doctag': TextStyle(color: Color(0xfffb6acb)),
  'quote': TextStyle(color: Color(0xfffb6acb)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xfffb6acb)),
  'regexp': TextStyle(color: Color(0xfffb6acb)),
  'function-title': TextStyle(color: Color(0xff40bfff)),
  'attribute': TextStyle(color: Color(0xff40bfff)),
  '.ruby-property': TextStyle(color: Color(0xff40bfff)),
  'title.function_': TextStyle(color: Color(0xff40bfff)),
  'section': TextStyle(color: Color(0xff40bfff)),
  'type': TextStyle(color: Color(0xffae94f9)),
  'template-tag': TextStyle(color: Color(0xffae94f9)),
  '.diff-meta': TextStyle(color: Color(0xffae94f9)),
  'keyword': TextStyle(color: Color(0xffae94f9)),
  'emphasis': TextStyle(color: Color(0xffae94f9), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff6187ff)),
  'meta-keyword':
      TextStyle(color: Color(0xff6187ff), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff6187ff)),
};
