// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const gruvboxDarkMediumTheme = {
  'root':
      TextStyle(color: Color(0xffd5c4a1), backgroundColor: Color(0xff282828)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff504945), color: Color(0xffd5c4a1)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff504945), color: Color(0xffd5c4a1)),
  'comment': TextStyle(color: Color(0xff665c54)),
  'tag': TextStyle(color: Color(0xffbdae93)),
  'subst': TextStyle(color: Color(0xffd5c4a1)),
  'punctuation': TextStyle(color: Color(0xffd5c4a1)),
  'operator': TextStyle(color: Color(0xffd5c4a1)),
  'bullet': TextStyle(color: Color(0xfffb4934)),
  'variable': TextStyle(color: Color(0xfffb4934)),
  'template-variable': TextStyle(color: Color(0xfffb4934)),
  'selector-tag': TextStyle(color: Color(0xfffb4934)),
  'name': TextStyle(color: Color(0xfffb4934)),
  'deletion': TextStyle(color: Color(0xfffb4934)),
  'symbol': TextStyle(color: Color(0xfffe8019)),
  'number': TextStyle(color: Color(0xfffe8019)),
  'link': TextStyle(color: Color(0xfffe8019)),
  'attr': TextStyle(color: Color(0xfffe8019)),
  'variable.constant_': TextStyle(color: Color(0xfffe8019)),
  'literal': TextStyle(color: Color(0xfffe8019)),
  'title': TextStyle(color: Color(0xfffabd2f)),
  'class-title': TextStyle(color: Color(0xfffabd2f)),
  'title.class_': TextStyle(color: Color(0xfffabd2f)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xfffabd2f)),
  'code': TextStyle(color: Color(0xffb8bb26)),
  'addition': TextStyle(color: Color(0xffb8bb26)),
  'title.class_.inherited__': TextStyle(color: Color(0xffb8bb26)),
  'string': TextStyle(color: Color(0xffb8bb26)),
  'built_in': TextStyle(color: Color(0xff8ec07c)),
  'doctag': TextStyle(color: Color(0xff8ec07c)),
  'quote': TextStyle(color: Color(0xff8ec07c)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff8ec07c)),
  'regexp': TextStyle(color: Color(0xff8ec07c)),
  'function-title': TextStyle(color: Color(0xff83a598)),
  'attribute': TextStyle(color: Color(0xff83a598)),
  '.ruby-property': TextStyle(color: Color(0xff83a598)),
  'title.function_': TextStyle(color: Color(0xff83a598)),
  'section': TextStyle(color: Color(0xff83a598)),
  'type': TextStyle(color: Color(0xffd3869b)),
  'template-tag': TextStyle(color: Color(0xffd3869b)),
  '.diff-meta': TextStyle(color: Color(0xffd3869b)),
  'keyword': TextStyle(color: Color(0xffd3869b)),
  'emphasis': TextStyle(color: Color(0xffd3869b), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffd65d0e)),
  'meta-keyword':
      TextStyle(color: Color(0xffd65d0e), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffd65d0e)),
};
