// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const hardcoreTheme = {
  'root':
      TextStyle(color: Color(0xffcdcdcd), backgroundColor: Color(0xff212121)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff353535), color: Color(0xffcdcdcd)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff353535), color: Color(0xffcdcdcd)),
  'comment': TextStyle(color: Color(0xff4A4A4A)),
  'tag': TextStyle(color: Color(0xff707070)),
  'subst': TextStyle(color: Color(0xffcdcdcd)),
  'punctuation': TextStyle(color: Color(0xffcdcdcd)),
  'operator': TextStyle(color: Color(0xffcdcdcd)),
  'bullet': TextStyle(color: Color(0xfff92672)),
  'variable': TextStyle(color: Color(0xfff92672)),
  'template-variable': TextStyle(color: Color(0xfff92672)),
  'selector-tag': TextStyle(color: Color(0xfff92672)),
  'name': TextStyle(color: Color(0xfff92672)),
  'deletion': TextStyle(color: Color(0xfff92672)),
  'symbol': TextStyle(color: Color(0xfffd971f)),
  'number': TextStyle(color: Color(0xfffd971f)),
  'link': TextStyle(color: Color(0xfffd971f)),
  'attr': TextStyle(color: Color(0xfffd971f)),
  'variable.constant_': TextStyle(color: Color(0xfffd971f)),
  'literal': TextStyle(color: Color(0xfffd971f)),
  'title': TextStyle(color: Color(0xffe6db74)),
  'class-title': TextStyle(color: Color(0xffe6db74)),
  'title.class_': TextStyle(color: Color(0xffe6db74)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffe6db74)),
  'code': TextStyle(color: Color(0xffa6e22e)),
  'addition': TextStyle(color: Color(0xffa6e22e)),
  'title.class_.inherited__': TextStyle(color: Color(0xffa6e22e)),
  'string': TextStyle(color: Color(0xffa6e22e)),
  'built_in': TextStyle(color: Color(0xff708387)),
  'doctag': TextStyle(color: Color(0xff708387)),
  'quote': TextStyle(color: Color(0xff708387)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff708387)),
  'regexp': TextStyle(color: Color(0xff708387)),
  'function-title': TextStyle(color: Color(0xff66d9ef)),
  'attribute': TextStyle(color: Color(0xff66d9ef)),
  '.ruby-property': TextStyle(color: Color(0xff66d9ef)),
  'title.function_': TextStyle(color: Color(0xff66d9ef)),
  'section': TextStyle(color: Color(0xff66d9ef)),
  'type': TextStyle(color: Color(0xff9e6ffe)),
  'template-tag': TextStyle(color: Color(0xff9e6ffe)),
  '.diff-meta': TextStyle(color: Color(0xff9e6ffe)),
  'keyword': TextStyle(color: Color(0xff9e6ffe)),
  'emphasis': TextStyle(color: Color(0xff9e6ffe), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffe8b882)),
  'meta-keyword':
      TextStyle(color: Color(0xffe8b882), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffe8b882)),
};
