// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const harmonic16DarkTheme = {
  'root':
      TextStyle(color: Color(0xffcbd6e2), backgroundColor: Color(0xff0b1c2c)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff405c79), color: Color(0xffcbd6e2)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff405c79), color: Color(0xffcbd6e2)),
  'comment': TextStyle(color: Color(0xff627e99)),
  'tag': TextStyle(color: Color(0xffaabcce)),
  'subst': TextStyle(color: Color(0xffcbd6e2)),
  'punctuation': TextStyle(color: Color(0xffcbd6e2)),
  'operator': TextStyle(color: Color(0xffcbd6e2)),
  'bullet': TextStyle(color: Color(0xffbf8b56)),
  'variable': TextStyle(color: Color(0xffbf8b56)),
  'template-variable': TextStyle(color: Color(0xffbf8b56)),
  'selector-tag': TextStyle(color: Color(0xffbf8b56)),
  'name': TextStyle(color: Color(0xffbf8b56)),
  'deletion': TextStyle(color: Color(0xffbf8b56)),
  'symbol': TextStyle(color: Color(0xffbfbf56)),
  'number': TextStyle(color: Color(0xffbfbf56)),
  'link': TextStyle(color: Color(0xffbfbf56)),
  'attr': TextStyle(color: Color(0xffbfbf56)),
  'variable.constant_': TextStyle(color: Color(0xffbfbf56)),
  'literal': TextStyle(color: Color(0xffbfbf56)),
  'title': TextStyle(color: Color(0xff8bbf56)),
  'class-title': TextStyle(color: Color(0xff8bbf56)),
  'title.class_': TextStyle(color: Color(0xff8bbf56)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff8bbf56)),
  'code': TextStyle(color: Color(0xff56bf8b)),
  'addition': TextStyle(color: Color(0xff56bf8b)),
  'title.class_.inherited__': TextStyle(color: Color(0xff56bf8b)),
  'string': TextStyle(color: Color(0xff56bf8b)),
  'built_in': TextStyle(color: Color(0xff568bbf)),
  'doctag': TextStyle(color: Color(0xff568bbf)),
  'quote': TextStyle(color: Color(0xff568bbf)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff568bbf)),
  'regexp': TextStyle(color: Color(0xff568bbf)),
  'function-title': TextStyle(color: Color(0xff8b56bf)),
  'attribute': TextStyle(color: Color(0xff8b56bf)),
  '.ruby-property': TextStyle(color: Color(0xff8b56bf)),
  'title.function_': TextStyle(color: Color(0xff8b56bf)),
  'section': TextStyle(color: Color(0xff8b56bf)),
  'type': TextStyle(color: Color(0xffbf568b)),
  'template-tag': TextStyle(color: Color(0xffbf568b)),
  '.diff-meta': TextStyle(color: Color(0xffbf568b)),
  'keyword': TextStyle(color: Color(0xffbf568b)),
  'emphasis': TextStyle(color: Color(0xffbf568b), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffbf5656)),
  'meta-keyword':
      TextStyle(color: Color(0xffbf5656), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffbf5656)),
};
