// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const heetchDarkTheme = {
  'root':
      TextStyle(color: Color(0xffBDB6C5), backgroundColor: Color(0xff190134)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff5A496E), color: Color(0xffBDB6C5)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff5A496E), color: Color(0xffBDB6C5)),
  'comment': TextStyle(color: Color(0xff7B6D8B)),
  'tag': TextStyle(color: Color(0xff9C92A8)),
  'subst': TextStyle(color: Color(0xffBDB6C5)),
  'punctuation': TextStyle(color: Color(0xffBDB6C5)),
  'operator': TextStyle(color: Color(0xffBDB6C5)),
  'bullet': TextStyle(color: Color(0xff27D9D5)),
  'variable': TextStyle(color: Color(0xff27D9D5)),
  'template-variable': TextStyle(color: Color(0xff27D9D5)),
  'selector-tag': TextStyle(color: Color(0xff27D9D5)),
  'name': TextStyle(color: Color(0xff27D9D5)),
  'deletion': TextStyle(color: Color(0xff27D9D5)),
  'symbol': TextStyle(color: Color(0xff5BA2B6)),
  'number': TextStyle(color: Color(0xff5BA2B6)),
  'link': TextStyle(color: Color(0xff5BA2B6)),
  'attr': TextStyle(color: Color(0xff5BA2B6)),
  'variable.constant_': TextStyle(color: Color(0xff5BA2B6)),
  'literal': TextStyle(color: Color(0xff5BA2B6)),
  'title': TextStyle(color: Color(0xff8F6C97)),
  'class-title': TextStyle(color: Color(0xff8F6C97)),
  'title.class_': TextStyle(color: Color(0xff8F6C97)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff8F6C97)),
  'code': TextStyle(color: Color(0xffC33678)),
  'addition': TextStyle(color: Color(0xffC33678)),
  'title.class_.inherited__': TextStyle(color: Color(0xffC33678)),
  'string': TextStyle(color: Color(0xffC33678)),
  'built_in': TextStyle(color: Color(0xffF80059)),
  'doctag': TextStyle(color: Color(0xffF80059)),
  'quote': TextStyle(color: Color(0xffF80059)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffF80059)),
  'regexp': TextStyle(color: Color(0xffF80059)),
  'function-title': TextStyle(color: Color(0xffBD0152)),
  'attribute': TextStyle(color: Color(0xffBD0152)),
  '.ruby-property': TextStyle(color: Color(0xffBD0152)),
  'title.function_': TextStyle(color: Color(0xffBD0152)),
  'section': TextStyle(color: Color(0xffBD0152)),
  'type': TextStyle(color: Color(0xff82034C)),
  'template-tag': TextStyle(color: Color(0xff82034C)),
  '.diff-meta': TextStyle(color: Color(0xff82034C)),
  'keyword': TextStyle(color: Color(0xff82034C)),
  'emphasis': TextStyle(color: Color(0xff82034C), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff470546)),
  'meta-keyword':
      TextStyle(color: Color(0xff470546), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff470546)),
};
