// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const horizonLightTheme = {
  'root':
      TextStyle(color: Color(0xff403C3D), backgroundColor: Color(0xffFDF0ED)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xffF9CBBE), color: Color(0xff403C3D)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xffF9CBBE), color: Color(0xff403C3D)),
  'comment': TextStyle(color: Color(0xffBDB3B1)),
  'tag': TextStyle(color: Color(0xff948C8A)),
  'subst': TextStyle(color: Color(0xff403C3D)),
  'punctuation': TextStyle(color: Color(0xff403C3D)),
  'operator': TextStyle(color: Color(0xff403C3D)),
  'bullet': TextStyle(color: Color(0xffE95678)),
  'variable': TextStyle(color: Color(0xffE95678)),
  'template-variable': TextStyle(color: Color(0xffE95678)),
  'selector-tag': TextStyle(color: Color(0xffE95678)),
  'name': TextStyle(color: Color(0xffE95678)),
  'deletion': TextStyle(color: Color(0xffE95678)),
  'symbol': TextStyle(color: Color(0xffF9CEC3)),
  'number': TextStyle(color: Color(0xffF9CEC3)),
  'link': TextStyle(color: Color(0xffF9CEC3)),
  'attr': TextStyle(color: Color(0xffF9CEC3)),
  'variable.constant_': TextStyle(color: Color(0xffF9CEC3)),
  'literal': TextStyle(color: Color(0xffF9CEC3)),
  'title': TextStyle(color: Color(0xffFADAD1)),
  'class-title': TextStyle(color: Color(0xffFADAD1)),
  'title.class_': TextStyle(color: Color(0xffFADAD1)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffFADAD1)),
  'code': TextStyle(color: Color(0xff29D398)),
  'addition': TextStyle(color: Color(0xff29D398)),
  'title.class_.inherited__': TextStyle(color: Color(0xff29D398)),
  'string': TextStyle(color: Color(0xff29D398)),
  'built_in': TextStyle(color: Color(0xff59E1E3)),
  'doctag': TextStyle(color: Color(0xff59E1E3)),
  'quote': TextStyle(color: Color(0xff59E1E3)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff59E1E3)),
  'regexp': TextStyle(color: Color(0xff59E1E3)),
  'function-title': TextStyle(color: Color(0xff26BBD9)),
  'attribute': TextStyle(color: Color(0xff26BBD9)),
  '.ruby-property': TextStyle(color: Color(0xff26BBD9)),
  'title.function_': TextStyle(color: Color(0xff26BBD9)),
  'section': TextStyle(color: Color(0xff26BBD9)),
  'type': TextStyle(color: Color(0xffEE64AC)),
  'template-tag': TextStyle(color: Color(0xffEE64AC)),
  '.diff-meta': TextStyle(color: Color(0xffEE64AC)),
  'keyword': TextStyle(color: Color(0xffEE64AC)),
  'emphasis': TextStyle(color: Color(0xffEE64AC), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffF9CBBE)),
  'meta-keyword':
      TextStyle(color: Color(0xffF9CBBE), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffF9CBBE)),
};
