// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const humanoidDarkTheme = {
  'root':
      TextStyle(color: Color(0xfff8f8f2), backgroundColor: Color(0xff232629)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff484e54), color: Color(0xfff8f8f2)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff484e54), color: Color(0xfff8f8f2)),
  'comment': TextStyle(color: Color(0xff60615d)),
  'tag': TextStyle(color: Color(0xffc0c0bd)),
  'subst': TextStyle(color: Color(0xfff8f8f2)),
  'punctuation': TextStyle(color: Color(0xfff8f8f2)),
  'operator': TextStyle(color: Color(0xfff8f8f2)),
  'bullet': TextStyle(color: Color(0xfff11235)),
  'variable': TextStyle(color: Color(0xfff11235)),
  'template-variable': TextStyle(color: Color(0xfff11235)),
  'selector-tag': TextStyle(color: Color(0xfff11235)),
  'name': TextStyle(color: Color(0xfff11235)),
  'deletion': TextStyle(color: Color(0xfff11235)),
  'symbol': TextStyle(color: Color(0xffff9505)),
  'number': TextStyle(color: Color(0xffff9505)),
  'link': TextStyle(color: Color(0xffff9505)),
  'attr': TextStyle(color: Color(0xffff9505)),
  'variable.constant_': TextStyle(color: Color(0xffff9505)),
  'literal': TextStyle(color: Color(0xffff9505)),
  'title': TextStyle(color: Color(0xffffb627)),
  'class-title': TextStyle(color: Color(0xffffb627)),
  'title.class_': TextStyle(color: Color(0xffffb627)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffffb627)),
  'code': TextStyle(color: Color(0xff02d849)),
  'addition': TextStyle(color: Color(0xff02d849)),
  'title.class_.inherited__': TextStyle(color: Color(0xff02d849)),
  'string': TextStyle(color: Color(0xff02d849)),
  'built_in': TextStyle(color: Color(0xff0dd9d6)),
  'doctag': TextStyle(color: Color(0xff0dd9d6)),
  'quote': TextStyle(color: Color(0xff0dd9d6)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff0dd9d6)),
  'regexp': TextStyle(color: Color(0xff0dd9d6)),
  'function-title': TextStyle(color: Color(0xff00a6fb)),
  'attribute': TextStyle(color: Color(0xff00a6fb)),
  '.ruby-property': TextStyle(color: Color(0xff00a6fb)),
  'title.function_': TextStyle(color: Color(0xff00a6fb)),
  'section': TextStyle(color: Color(0xff00a6fb)),
  'type': TextStyle(color: Color(0xfff15ee3)),
  'template-tag': TextStyle(color: Color(0xfff15ee3)),
  '.diff-meta': TextStyle(color: Color(0xfff15ee3)),
  'keyword': TextStyle(color: Color(0xfff15ee3)),
  'emphasis': TextStyle(color: Color(0xfff15ee3), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffb27701)),
  'meta-keyword':
      TextStyle(color: Color(0xffb27701), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffb27701)),
};
