// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const iaLightTheme = {
  'root':
      TextStyle(color: Color(0xff181818), backgroundColor: Color(0xfff6f6f6)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xffbde5f2), color: Color(0xff181818)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xffbde5f2), color: Color(0xff181818)),
  'comment': TextStyle(color: Color(0xff898989)),
  'tag': TextStyle(color: Color(0xff767676)),
  'subst': TextStyle(color: Color(0xff181818)),
  'punctuation': TextStyle(color: Color(0xff181818)),
  'operator': TextStyle(color: Color(0xff181818)),
  'bullet': TextStyle(color: Color(0xff9c5a02)),
  'variable': TextStyle(color: Color(0xff9c5a02)),
  'template-variable': TextStyle(color: Color(0xff9c5a02)),
  'selector-tag': TextStyle(color: Color(0xff9c5a02)),
  'name': TextStyle(color: Color(0xff9c5a02)),
  'deletion': TextStyle(color: Color(0xff9c5a02)),
  'symbol': TextStyle(color: Color(0xffc43e18)),
  'number': TextStyle(color: Color(0xffc43e18)),
  'link': TextStyle(color: Color(0xffc43e18)),
  'attr': TextStyle(color: Color(0xffc43e18)),
  'variable.constant_': TextStyle(color: Color(0xffc43e18)),
  'literal': TextStyle(color: Color(0xffc43e18)),
  'title': TextStyle(color: Color(0xffc48218)),
  'class-title': TextStyle(color: Color(0xffc48218)),
  'title.class_': TextStyle(color: Color(0xffc48218)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffc48218)),
  'code': TextStyle(color: Color(0xff38781c)),
  'addition': TextStyle(color: Color(0xff38781c)),
  'title.class_.inherited__': TextStyle(color: Color(0xff38781c)),
  'string': TextStyle(color: Color(0xff38781c)),
  'built_in': TextStyle(color: Color(0xff2d6bb1)),
  'doctag': TextStyle(color: Color(0xff2d6bb1)),
  'quote': TextStyle(color: Color(0xff2d6bb1)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff2d6bb1)),
  'regexp': TextStyle(color: Color(0xff2d6bb1)),
  'function-title': TextStyle(color: Color(0xff48bac2)),
  'attribute': TextStyle(color: Color(0xff48bac2)),
  '.ruby-property': TextStyle(color: Color(0xff48bac2)),
  'title.function_': TextStyle(color: Color(0xff48bac2)),
  'section': TextStyle(color: Color(0xff48bac2)),
  'type': TextStyle(color: Color(0xffa94598)),
  'template-tag': TextStyle(color: Color(0xffa94598)),
  '.diff-meta': TextStyle(color: Color(0xffa94598)),
  'keyword': TextStyle(color: Color(0xffa94598)),
  'emphasis': TextStyle(color: Color(0xffa94598), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff8b6c37)),
  'meta-keyword':
      TextStyle(color: Color(0xff8b6c37), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff8b6c37)),
};
