// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const icyDarkTheme = {
  'root':
      TextStyle(color: Color(0xff095b67), backgroundColor: Color(0xff021012)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff041f23), color: Color(0xff095b67)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff041f23), color: Color(0xff095b67)),
  'comment': TextStyle(color: Color(0xff052e34)),
  'tag': TextStyle(color: Color(0xff064048)),
  'subst': TextStyle(color: Color(0xff095b67)),
  'punctuation': TextStyle(color: Color(0xff095b67)),
  'operator': TextStyle(color: Color(0xff095b67)),
  'bullet': TextStyle(color: Color(0xff16c1d9)),
  'variable': TextStyle(color: Color(0xff16c1d9)),
  'template-variable': TextStyle(color: Color(0xff16c1d9)),
  'selector-tag': TextStyle(color: Color(0xff16c1d9)),
  'name': TextStyle(color: Color(0xff16c1d9)),
  'deletion': TextStyle(color: Color(0xff16c1d9)),
  'symbol': TextStyle(color: Color(0xffb3ebf2)),
  'number': TextStyle(color: Color(0xffb3ebf2)),
  'link': TextStyle(color: Color(0xffb3ebf2)),
  'attr': TextStyle(color: Color(0xffb3ebf2)),
  'variable.constant_': TextStyle(color: Color(0xffb3ebf2)),
  'literal': TextStyle(color: Color(0xffb3ebf2)),
  'title': TextStyle(color: Color(0xff80deea)),
  'class-title': TextStyle(color: Color(0xff80deea)),
  'title.class_': TextStyle(color: Color(0xff80deea)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xff80deea)),
  'code': TextStyle(color: Color(0xff4dd0e1)),
  'addition': TextStyle(color: Color(0xff4dd0e1)),
  'title.class_.inherited__': TextStyle(color: Color(0xff4dd0e1)),
  'string': TextStyle(color: Color(0xff4dd0e1)),
  'built_in': TextStyle(color: Color(0xff26c6da)),
  'doctag': TextStyle(color: Color(0xff26c6da)),
  'quote': TextStyle(color: Color(0xff26c6da)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff26c6da)),
  'regexp': TextStyle(color: Color(0xff26c6da)),
  'function-title': TextStyle(color: Color(0xff00bcd4)),
  'attribute': TextStyle(color: Color(0xff00bcd4)),
  '.ruby-property': TextStyle(color: Color(0xff00bcd4)),
  'title.function_': TextStyle(color: Color(0xff00bcd4)),
  'section': TextStyle(color: Color(0xff00bcd4)),
  'type': TextStyle(color: Color(0xff00acc1)),
  'template-tag': TextStyle(color: Color(0xff00acc1)),
  '.diff-meta': TextStyle(color: Color(0xff00acc1)),
  'keyword': TextStyle(color: Color(0xff00acc1)),
  'emphasis': TextStyle(color: Color(0xff00acc1), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff0097a7)),
  'meta-keyword':
      TextStyle(color: Color(0xff0097a7), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff0097a7)),
};
