// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const irBlackTheme = {
  'root':
      TextStyle(color: Color(0xffb5b3aa), backgroundColor: Color(0xff000000)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff484844), color: Color(0xffb5b3aa)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff484844), color: Color(0xffb5b3aa)),
  'comment': TextStyle(color: Color(0xff6c6c66)),
  'tag': TextStyle(color: Color(0xff918f88)),
  'subst': TextStyle(color: Color(0xffb5b3aa)),
  'punctuation': TextStyle(color: Color(0xffb5b3aa)),
  'operator': TextStyle(color: Color(0xffb5b3aa)),
  'bullet': TextStyle(color: Color(0xffff6c60)),
  'variable': TextStyle(color: Color(0xffff6c60)),
  'template-variable': TextStyle(color: Color(0xffff6c60)),
  'selector-tag': TextStyle(color: Color(0xffff6c60)),
  'name': TextStyle(color: Color(0xffff6c60)),
  'deletion': TextStyle(color: Color(0xffff6c60)),
  'symbol': TextStyle(color: Color(0xffe9c062)),
  'number': TextStyle(color: Color(0xffe9c062)),
  'link': TextStyle(color: Color(0xffe9c062)),
  'attr': TextStyle(color: Color(0xffe9c062)),
  'variable.constant_': TextStyle(color: Color(0xffe9c062)),
  'literal': TextStyle(color: Color(0xffe9c062)),
  'title': TextStyle(color: Color(0xffffffb6)),
  'class-title': TextStyle(color: Color(0xffffffb6)),
  'title.class_': TextStyle(color: Color(0xffffffb6)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffffffb6)),
  'code': TextStyle(color: Color(0xffa8ff60)),
  'addition': TextStyle(color: Color(0xffa8ff60)),
  'title.class_.inherited__': TextStyle(color: Color(0xffa8ff60)),
  'string': TextStyle(color: Color(0xffa8ff60)),
  'built_in': TextStyle(color: Color(0xffc6c5fe)),
  'doctag': TextStyle(color: Color(0xffc6c5fe)),
  'quote': TextStyle(color: Color(0xffc6c5fe)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffc6c5fe)),
  'regexp': TextStyle(color: Color(0xffc6c5fe)),
  'function-title': TextStyle(color: Color(0xff96cbfe)),
  'attribute': TextStyle(color: Color(0xff96cbfe)),
  '.ruby-property': TextStyle(color: Color(0xff96cbfe)),
  'title.function_': TextStyle(color: Color(0xff96cbfe)),
  'section': TextStyle(color: Color(0xff96cbfe)),
  'type': TextStyle(color: Color(0xffff73fd)),
  'template-tag': TextStyle(color: Color(0xffff73fd)),
  '.diff-meta': TextStyle(color: Color(0xffff73fd)),
  'keyword': TextStyle(color: Color(0xffff73fd)),
  'emphasis': TextStyle(color: Color(0xffff73fd), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffb18a3d)),
  'meta-keyword':
      TextStyle(color: Color(0xffb18a3d), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffb18a3d)),
};
