// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const materiaTheme = {
  'root':
      TextStyle(color: Color(0xffCDD3DE), backgroundColor: Color(0xff263238)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff37474F), color: Color(0xffCDD3DE)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff37474F), color: Color(0xffCDD3DE)),
  'comment': TextStyle(color: Color(0xff707880)),
  'tag': TextStyle(color: Color(0xffC9CCD3)),
  'subst': TextStyle(color: Color(0xffCDD3DE)),
  'punctuation': TextStyle(color: Color(0xffCDD3DE)),
  'operator': TextStyle(color: Color(0xffCDD3DE)),
  'bullet': TextStyle(color: Color(0xffEC5F67)),
  'variable': TextStyle(color: Color(0xffEC5F67)),
  'template-variable': TextStyle(color: Color(0xffEC5F67)),
  'selector-tag': TextStyle(color: Color(0xffEC5F67)),
  'name': TextStyle(color: Color(0xffEC5F67)),
  'deletion': TextStyle(color: Color(0xffEC5F67)),
  'symbol': TextStyle(color: Color(0xffEA9560)),
  'number': TextStyle(color: Color(0xffEA9560)),
  'link': TextStyle(color: Color(0xffEA9560)),
  'attr': TextStyle(color: Color(0xffEA9560)),
  'variable.constant_': TextStyle(color: Color(0xffEA9560)),
  'literal': TextStyle(color: Color(0xffEA9560)),
  'title': TextStyle(color: Color(0xffFFCC00)),
  'class-title': TextStyle(color: Color(0xffFFCC00)),
  'title.class_': TextStyle(color: Color(0xffFFCC00)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffFFCC00)),
  'code': TextStyle(color: Color(0xff8BD649)),
  'addition': TextStyle(color: Color(0xff8BD649)),
  'title.class_.inherited__': TextStyle(color: Color(0xff8BD649)),
  'string': TextStyle(color: Color(0xff8BD649)),
  'built_in': TextStyle(color: Color(0xff80CBC4)),
  'doctag': TextStyle(color: Color(0xff80CBC4)),
  'quote': TextStyle(color: Color(0xff80CBC4)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff80CBC4)),
  'regexp': TextStyle(color: Color(0xff80CBC4)),
  'function-title': TextStyle(color: Color(0xff89DDFF)),
  'attribute': TextStyle(color: Color(0xff89DDFF)),
  '.ruby-property': TextStyle(color: Color(0xff89DDFF)),
  'title.function_': TextStyle(color: Color(0xff89DDFF)),
  'section': TextStyle(color: Color(0xff89DDFF)),
  'type': TextStyle(color: Color(0xff82AAFF)),
  'template-tag': TextStyle(color: Color(0xff82AAFF)),
  '.diff-meta': TextStyle(color: Color(0xff82AAFF)),
  'keyword': TextStyle(color: Color(0xff82AAFF)),
  'emphasis': TextStyle(color: Color(0xff82AAFF), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffEC5F67)),
  'meta-keyword':
      TextStyle(color: Color(0xffEC5F67), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffEC5F67)),
};
