// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const materialLighterTheme = {
  'root':
      TextStyle(color: Color(0xff80CBC4), backgroundColor: Color(0xffFAFAFA)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xffCCEAE7), color: Color(0xff80CBC4)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xffCCEAE7), color: Color(0xff80CBC4)),
  'comment': TextStyle(color: Color(0xffCCD7DA)),
  'tag': TextStyle(color: Color(0xff8796B0)),
  'subst': TextStyle(color: Color(0xff80CBC4)),
  'punctuation': TextStyle(color: Color(0xff80CBC4)),
  'operator': TextStyle(color: Color(0xff80CBC4)),
  'bullet': TextStyle(color: Color(0xffFF5370)),
  'variable': TextStyle(color: Color(0xffFF5370)),
  'template-variable': TextStyle(color: Color(0xffFF5370)),
  'selector-tag': TextStyle(color: Color(0xffFF5370)),
  'name': TextStyle(color: Color(0xffFF5370)),
  'deletion': TextStyle(color: Color(0xffFF5370)),
  'symbol': TextStyle(color: Color(0xffF76D47)),
  'number': TextStyle(color: Color(0xffF76D47)),
  'link': TextStyle(color: Color(0xffF76D47)),
  'attr': TextStyle(color: Color(0xffF76D47)),
  'variable.constant_': TextStyle(color: Color(0xffF76D47)),
  'literal': TextStyle(color: Color(0xffF76D47)),
  'title': TextStyle(color: Color(0xffFFB62C)),
  'class-title': TextStyle(color: Color(0xffFFB62C)),
  'title.class_': TextStyle(color: Color(0xffFFB62C)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffFFB62C)),
  'code': TextStyle(color: Color(0xff91B859)),
  'addition': TextStyle(color: Color(0xff91B859)),
  'title.class_.inherited__': TextStyle(color: Color(0xff91B859)),
  'string': TextStyle(color: Color(0xff91B859)),
  'built_in': TextStyle(color: Color(0xff39ADB5)),
  'doctag': TextStyle(color: Color(0xff39ADB5)),
  'quote': TextStyle(color: Color(0xff39ADB5)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff39ADB5)),
  'regexp': TextStyle(color: Color(0xff39ADB5)),
  'function-title': TextStyle(color: Color(0xff6182B8)),
  'attribute': TextStyle(color: Color(0xff6182B8)),
  '.ruby-property': TextStyle(color: Color(0xff6182B8)),
  'title.function_': TextStyle(color: Color(0xff6182B8)),
  'section': TextStyle(color: Color(0xff6182B8)),
  'type': TextStyle(color: Color(0xff7C4DFF)),
  'template-tag': TextStyle(color: Color(0xff7C4DFF)),
  '.diff-meta': TextStyle(color: Color(0xff7C4DFF)),
  'keyword': TextStyle(color: Color(0xff7C4DFF)),
  'emphasis': TextStyle(color: Color(0xff7C4DFF), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffE53935)),
  'meta-keyword':
      TextStyle(color: Color(0xffE53935), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffE53935)),
};
