// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const monokaiTheme = {
  'root':
      TextStyle(color: Color(0xfff8f8f2), backgroundColor: Color(0xff272822)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff49483e), color: Color(0xfff8f8f2)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff49483e), color: Color(0xfff8f8f2)),
  'comment': TextStyle(color: Color(0xff75715e)),
  'tag': TextStyle(color: Color(0xffa59f85)),
  'subst': TextStyle(color: Color(0xfff8f8f2)),
  'punctuation': TextStyle(color: Color(0xfff8f8f2)),
  'operator': TextStyle(color: Color(0xfff8f8f2)),
  'bullet': TextStyle(color: Color(0xfff92672)),
  'variable': TextStyle(color: Color(0xfff92672)),
  'template-variable': TextStyle(color: Color(0xfff92672)),
  'selector-tag': TextStyle(color: Color(0xfff92672)),
  'name': TextStyle(color: Color(0xfff92672)),
  'deletion': TextStyle(color: Color(0xfff92672)),
  'symbol': TextStyle(color: Color(0xfffd971f)),
  'number': TextStyle(color: Color(0xfffd971f)),
  'link': TextStyle(color: Color(0xfffd971f)),
  'attr': TextStyle(color: Color(0xfffd971f)),
  'variable.constant_': TextStyle(color: Color(0xfffd971f)),
  'literal': TextStyle(color: Color(0xfffd971f)),
  'title': TextStyle(color: Color(0xfff4bf75)),
  'class-title': TextStyle(color: Color(0xfff4bf75)),
  'title.class_': TextStyle(color: Color(0xfff4bf75)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xfff4bf75)),
  'code': TextStyle(color: Color(0xffa6e22e)),
  'addition': TextStyle(color: Color(0xffa6e22e)),
  'title.class_.inherited__': TextStyle(color: Color(0xffa6e22e)),
  'string': TextStyle(color: Color(0xffa6e22e)),
  'built_in': TextStyle(color: Color(0xffa1efe4)),
  'doctag': TextStyle(color: Color(0xffa1efe4)),
  'quote': TextStyle(color: Color(0xffa1efe4)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffa1efe4)),
  'regexp': TextStyle(color: Color(0xffa1efe4)),
  'function-title': TextStyle(color: Color(0xff66d9ef)),
  'attribute': TextStyle(color: Color(0xff66d9ef)),
  '.ruby-property': TextStyle(color: Color(0xff66d9ef)),
  'title.function_': TextStyle(color: Color(0xff66d9ef)),
  'section': TextStyle(color: Color(0xff66d9ef)),
  'type': TextStyle(color: Color(0xffae81ff)),
  'template-tag': TextStyle(color: Color(0xffae81ff)),
  '.diff-meta': TextStyle(color: Color(0xffae81ff)),
  'keyword': TextStyle(color: Color(0xffae81ff)),
  'emphasis': TextStyle(color: Color(0xffae81ff), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffcc6633)),
  'meta-keyword':
      TextStyle(color: Color(0xffcc6633), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffcc6633)),
};
