// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const oceanicnextTheme = {
  'root':
      TextStyle(color: Color(0xffC0C5CE), backgroundColor: Color(0xff1B2B34)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff4F5B66), color: Color(0xffC0C5CE)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff4F5B66), color: Color(0xffC0C5CE)),
  'comment': TextStyle(color: Color(0xff65737E)),
  'tag': TextStyle(color: Color(0xffA7ADBA)),
  'subst': TextStyle(color: Color(0xffC0C5CE)),
  'punctuation': TextStyle(color: Color(0xffC0C5CE)),
  'operator': TextStyle(color: Color(0xffC0C5CE)),
  'bullet': TextStyle(color: Color(0xffEC5f67)),
  'variable': TextStyle(color: Color(0xffEC5f67)),
  'template-variable': TextStyle(color: Color(0xffEC5f67)),
  'selector-tag': TextStyle(color: Color(0xffEC5f67)),
  'name': TextStyle(color: Color(0xffEC5f67)),
  'deletion': TextStyle(color: Color(0xffEC5f67)),
  'symbol': TextStyle(color: Color(0xffF99157)),
  'number': TextStyle(color: Color(0xffF99157)),
  'link': TextStyle(color: Color(0xffF99157)),
  'attr': TextStyle(color: Color(0xffF99157)),
  'variable.constant_': TextStyle(color: Color(0xffF99157)),
  'literal': TextStyle(color: Color(0xffF99157)),
  'title': TextStyle(color: Color(0xffFAC863)),
  'class-title': TextStyle(color: Color(0xffFAC863)),
  'title.class_': TextStyle(color: Color(0xffFAC863)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffFAC863)),
  'code': TextStyle(color: Color(0xff99C794)),
  'addition': TextStyle(color: Color(0xff99C794)),
  'title.class_.inherited__': TextStyle(color: Color(0xff99C794)),
  'string': TextStyle(color: Color(0xff99C794)),
  'built_in': TextStyle(color: Color(0xff5FB3B3)),
  'doctag': TextStyle(color: Color(0xff5FB3B3)),
  'quote': TextStyle(color: Color(0xff5FB3B3)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff5FB3B3)),
  'regexp': TextStyle(color: Color(0xff5FB3B3)),
  'function-title': TextStyle(color: Color(0xff6699CC)),
  'attribute': TextStyle(color: Color(0xff6699CC)),
  '.ruby-property': TextStyle(color: Color(0xff6699CC)),
  'title.function_': TextStyle(color: Color(0xff6699CC)),
  'section': TextStyle(color: Color(0xff6699CC)),
  'type': TextStyle(color: Color(0xffC594C5)),
  'template-tag': TextStyle(color: Color(0xffC594C5)),
  '.diff-meta': TextStyle(color: Color(0xffC594C5)),
  'keyword': TextStyle(color: Color(0xffC594C5)),
  'emphasis': TextStyle(color: Color(0xffC594C5), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffAB7967)),
  'meta-keyword':
      TextStyle(color: Color(0xffAB7967), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffAB7967)),
};
