// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const paraisoTheme = {
  'root':
      TextStyle(color: Color(0xffa39e9b), backgroundColor: Color(0xff2f1e2e)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff4f424c), color: Color(0xffa39e9b)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff4f424c), color: Color(0xffa39e9b)),
  'comment': TextStyle(color: Color(0xff776e71)),
  'tag': TextStyle(color: Color(0xff8d8687)),
  'subst': TextStyle(color: Color(0xffa39e9b)),
  'punctuation': TextStyle(color: Color(0xffa39e9b)),
  'operator': TextStyle(color: Color(0xffa39e9b)),
  'bullet': TextStyle(color: Color(0xffef6155)),
  'variable': TextStyle(color: Color(0xffef6155)),
  'template-variable': TextStyle(color: Color(0xffef6155)),
  'selector-tag': TextStyle(color: Color(0xffef6155)),
  'name': TextStyle(color: Color(0xffef6155)),
  'deletion': TextStyle(color: Color(0xffef6155)),
  'symbol': TextStyle(color: Color(0xfff99b15)),
  'number': TextStyle(color: Color(0xfff99b15)),
  'link': TextStyle(color: Color(0xfff99b15)),
  'attr': TextStyle(color: Color(0xfff99b15)),
  'variable.constant_': TextStyle(color: Color(0xfff99b15)),
  'literal': TextStyle(color: Color(0xfff99b15)),
  'title': TextStyle(color: Color(0xfffec418)),
  'class-title': TextStyle(color: Color(0xfffec418)),
  'title.class_': TextStyle(color: Color(0xfffec418)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xfffec418)),
  'code': TextStyle(color: Color(0xff48b685)),
  'addition': TextStyle(color: Color(0xff48b685)),
  'title.class_.inherited__': TextStyle(color: Color(0xff48b685)),
  'string': TextStyle(color: Color(0xff48b685)),
  'built_in': TextStyle(color: Color(0xff5bc4bf)),
  'doctag': TextStyle(color: Color(0xff5bc4bf)),
  'quote': TextStyle(color: Color(0xff5bc4bf)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff5bc4bf)),
  'regexp': TextStyle(color: Color(0xff5bc4bf)),
  'function-title': TextStyle(color: Color(0xff06b6ef)),
  'attribute': TextStyle(color: Color(0xff06b6ef)),
  '.ruby-property': TextStyle(color: Color(0xff06b6ef)),
  'title.function_': TextStyle(color: Color(0xff06b6ef)),
  'section': TextStyle(color: Color(0xff06b6ef)),
  'type': TextStyle(color: Color(0xff815ba4)),
  'template-tag': TextStyle(color: Color(0xff815ba4)),
  '.diff-meta': TextStyle(color: Color(0xff815ba4)),
  'keyword': TextStyle(color: Color(0xff815ba4)),
  'emphasis': TextStyle(color: Color(0xff815ba4), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffe96ba8)),
  'meta-keyword':
      TextStyle(color: Color(0xffe96ba8), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffe96ba8)),
};
