// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const rosPineDawnTheme = {
  'root':
      TextStyle(color: Color(0xff575279), backgroundColor: Color(0xfffaf4ed)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xfff2e9de), color: Color(0xff575279)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xfff2e9de), color: Color(0xff575279)),
  'comment': TextStyle(color: Color(0xff9893a5)),
  'tag': TextStyle(color: Color(0xff6e6a86)),
  'subst': TextStyle(color: Color(0xff575279)),
  'punctuation': TextStyle(color: Color(0xff575279)),
  'operator': TextStyle(color: Color(0xff575279)),
  'bullet': TextStyle(color: Color(0xff1f1d2e)),
  'variable': TextStyle(color: Color(0xff1f1d2e)),
  'template-variable': TextStyle(color: Color(0xff1f1d2e)),
  'selector-tag': TextStyle(color: Color(0xff1f1d2e)),
  'name': TextStyle(color: Color(0xff1f1d2e)),
  'deletion': TextStyle(color: Color(0xff1f1d2e)),
  'symbol': TextStyle(color: Color(0xffb4637a)),
  'number': TextStyle(color: Color(0xffb4637a)),
  'link': TextStyle(color: Color(0xffb4637a)),
  'attr': TextStyle(color: Color(0xffb4637a)),
  'variable.constant_': TextStyle(color: Color(0xffb4637a)),
  'literal': TextStyle(color: Color(0xffb4637a)),
  'title': TextStyle(color: Color(0xffea9d34)),
  'class-title': TextStyle(color: Color(0xffea9d34)),
  'title.class_': TextStyle(color: Color(0xffea9d34)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffea9d34)),
  'code': TextStyle(color: Color(0xffd7827e)),
  'addition': TextStyle(color: Color(0xffd7827e)),
  'title.class_.inherited__': TextStyle(color: Color(0xffd7827e)),
  'string': TextStyle(color: Color(0xffd7827e)),
  'built_in': TextStyle(color: Color(0xff286983)),
  'doctag': TextStyle(color: Color(0xff286983)),
  'quote': TextStyle(color: Color(0xff286983)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff286983)),
  'regexp': TextStyle(color: Color(0xff286983)),
  'function-title': TextStyle(color: Color(0xff56949f)),
  'attribute': TextStyle(color: Color(0xff56949f)),
  '.ruby-property': TextStyle(color: Color(0xff56949f)),
  'title.function_': TextStyle(color: Color(0xff56949f)),
  'section': TextStyle(color: Color(0xff56949f)),
  'type': TextStyle(color: Color(0xff907aa9)),
  'template-tag': TextStyle(color: Color(0xff907aa9)),
  '.diff-meta': TextStyle(color: Color(0xff907aa9)),
  'keyword': TextStyle(color: Color(0xff907aa9)),
  'emphasis': TextStyle(color: Color(0xff907aa9), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffc5c3ce)),
  'meta-keyword':
      TextStyle(color: Color(0xffc5c3ce), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffc5c3ce)),
};
