// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const shapeshifterTheme = {
  'root':
      TextStyle(color: Color(0xff102015), backgroundColor: Color(0xfff9f9f9)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xffababab), color: Color(0xff102015)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xffababab), color: Color(0xff102015)),
  'comment': TextStyle(color: Color(0xff555555)),
  'tag': TextStyle(color: Color(0xff343434)),
  'subst': TextStyle(color: Color(0xff102015)),
  'punctuation': TextStyle(color: Color(0xff102015)),
  'operator': TextStyle(color: Color(0xff102015)),
  'bullet': TextStyle(color: Color(0xffe92f2f)),
  'variable': TextStyle(color: Color(0xffe92f2f)),
  'template-variable': TextStyle(color: Color(0xffe92f2f)),
  'selector-tag': TextStyle(color: Color(0xffe92f2f)),
  'name': TextStyle(color: Color(0xffe92f2f)),
  'deletion': TextStyle(color: Color(0xffe92f2f)),
  'symbol': TextStyle(color: Color(0xffe09448)),
  'number': TextStyle(color: Color(0xffe09448)),
  'link': TextStyle(color: Color(0xffe09448)),
  'attr': TextStyle(color: Color(0xffe09448)),
  'variable.constant_': TextStyle(color: Color(0xffe09448)),
  'literal': TextStyle(color: Color(0xffe09448)),
  'title': TextStyle(color: Color(0xffdddd13)),
  'class-title': TextStyle(color: Color(0xffdddd13)),
  'title.class_': TextStyle(color: Color(0xffdddd13)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffdddd13)),
  'code': TextStyle(color: Color(0xff0ed839)),
  'addition': TextStyle(color: Color(0xff0ed839)),
  'title.class_.inherited__': TextStyle(color: Color(0xff0ed839)),
  'string': TextStyle(color: Color(0xff0ed839)),
  'built_in': TextStyle(color: Color(0xff23edda)),
  'doctag': TextStyle(color: Color(0xff23edda)),
  'quote': TextStyle(color: Color(0xff23edda)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff23edda)),
  'regexp': TextStyle(color: Color(0xff23edda)),
  'function-title': TextStyle(color: Color(0xff3b48e3)),
  'attribute': TextStyle(color: Color(0xff3b48e3)),
  '.ruby-property': TextStyle(color: Color(0xff3b48e3)),
  'title.function_': TextStyle(color: Color(0xff3b48e3)),
  'section': TextStyle(color: Color(0xff3b48e3)),
  'type': TextStyle(color: Color(0xfff996e2)),
  'template-tag': TextStyle(color: Color(0xfff996e2)),
  '.diff-meta': TextStyle(color: Color(0xfff996e2)),
  'keyword': TextStyle(color: Color(0xfff996e2)),
  'emphasis': TextStyle(color: Color(0xfff996e2), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff69542d)),
  'meta-keyword':
      TextStyle(color: Color(0xff69542d), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff69542d)),
};
