// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const silkLightTheme = {
  'root':
      TextStyle(color: Color(0xff385156), backgroundColor: Color(0xffE9F1EF)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff90B7B6), color: Color(0xff385156)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff90B7B6), color: Color(0xff385156)),
  'comment': TextStyle(color: Color(0xff5C787B)),
  'tag': TextStyle(color: Color(0xff4B5B5F)),
  'subst': TextStyle(color: Color(0xff385156)),
  'punctuation': TextStyle(color: Color(0xff385156)),
  'operator': TextStyle(color: Color(0xff385156)),
  'bullet': TextStyle(color: Color(0xffCF432E)),
  'variable': TextStyle(color: Color(0xffCF432E)),
  'template-variable': TextStyle(color: Color(0xffCF432E)),
  'selector-tag': TextStyle(color: Color(0xffCF432E)),
  'name': TextStyle(color: Color(0xffCF432E)),
  'deletion': TextStyle(color: Color(0xffCF432E)),
  'symbol': TextStyle(color: Color(0xffD27F46)),
  'number': TextStyle(color: Color(0xffD27F46)),
  'link': TextStyle(color: Color(0xffD27F46)),
  'attr': TextStyle(color: Color(0xffD27F46)),
  'variable.constant_': TextStyle(color: Color(0xffD27F46)),
  'literal': TextStyle(color: Color(0xffD27F46)),
  'title': TextStyle(color: Color(0xffCFAD25)),
  'class-title': TextStyle(color: Color(0xffCFAD25)),
  'title.class_': TextStyle(color: Color(0xffCFAD25)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffCFAD25)),
  'code': TextStyle(color: Color(0xff6CA38C)),
  'addition': TextStyle(color: Color(0xff6CA38C)),
  'title.class_.inherited__': TextStyle(color: Color(0xff6CA38C)),
  'string': TextStyle(color: Color(0xff6CA38C)),
  'built_in': TextStyle(color: Color(0xff329CA2)),
  'doctag': TextStyle(color: Color(0xff329CA2)),
  'quote': TextStyle(color: Color(0xff329CA2)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff329CA2)),
  'regexp': TextStyle(color: Color(0xff329CA2)),
  'function-title': TextStyle(color: Color(0xff39AAC9)),
  'attribute': TextStyle(color: Color(0xff39AAC9)),
  '.ruby-property': TextStyle(color: Color(0xff39AAC9)),
  'title.function_': TextStyle(color: Color(0xff39AAC9)),
  'section': TextStyle(color: Color(0xff39AAC9)),
  'type': TextStyle(color: Color(0xff6E6582)),
  'template-tag': TextStyle(color: Color(0xff6E6582)),
  '.diff-meta': TextStyle(color: Color(0xff6E6582)),
  'keyword': TextStyle(color: Color(0xff6E6582)),
  'emphasis': TextStyle(color: Color(0xff6E6582), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff865369)),
  'meta-keyword':
      TextStyle(color: Color(0xff865369), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff865369)),
};
