// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const solarizedDarkTheme = {
  'root':
      TextStyle(color: Color(0xff93a1a1), backgroundColor: Color(0xff002b36)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff586e75), color: Color(0xff93a1a1)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff586e75), color: Color(0xff93a1a1)),
  'comment': TextStyle(color: Color(0xff657b83)),
  'tag': TextStyle(color: Color(0xff839496)),
  'subst': TextStyle(color: Color(0xff93a1a1)),
  'punctuation': TextStyle(color: Color(0xff93a1a1)),
  'operator': TextStyle(color: Color(0xff93a1a1)),
  'bullet': TextStyle(color: Color(0xffdc322f)),
  'variable': TextStyle(color: Color(0xffdc322f)),
  'template-variable': TextStyle(color: Color(0xffdc322f)),
  'selector-tag': TextStyle(color: Color(0xffdc322f)),
  'name': TextStyle(color: Color(0xffdc322f)),
  'deletion': TextStyle(color: Color(0xffdc322f)),
  'symbol': TextStyle(color: Color(0xffcb4b16)),
  'number': TextStyle(color: Color(0xffcb4b16)),
  'link': TextStyle(color: Color(0xffcb4b16)),
  'attr': TextStyle(color: Color(0xffcb4b16)),
  'variable.constant_': TextStyle(color: Color(0xffcb4b16)),
  'literal': TextStyle(color: Color(0xffcb4b16)),
  'title': TextStyle(color: Color(0xffb58900)),
  'class-title': TextStyle(color: Color(0xffb58900)),
  'title.class_': TextStyle(color: Color(0xffb58900)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffb58900)),
  'code': TextStyle(color: Color(0xff859900)),
  'addition': TextStyle(color: Color(0xff859900)),
  'title.class_.inherited__': TextStyle(color: Color(0xff859900)),
  'string': TextStyle(color: Color(0xff859900)),
  'built_in': TextStyle(color: Color(0xff2aa198)),
  'doctag': TextStyle(color: Color(0xff2aa198)),
  'quote': TextStyle(color: Color(0xff2aa198)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff2aa198)),
  'regexp': TextStyle(color: Color(0xff2aa198)),
  'function-title': TextStyle(color: Color(0xff268bd2)),
  'attribute': TextStyle(color: Color(0xff268bd2)),
  '.ruby-property': TextStyle(color: Color(0xff268bd2)),
  'title.function_': TextStyle(color: Color(0xff268bd2)),
  'section': TextStyle(color: Color(0xff268bd2)),
  'type': TextStyle(color: Color(0xff6c71c4)),
  'template-tag': TextStyle(color: Color(0xff6c71c4)),
  '.diff-meta': TextStyle(color: Color(0xff6c71c4)),
  'keyword': TextStyle(color: Color(0xff6c71c4)),
  'emphasis': TextStyle(color: Color(0xff6c71c4), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffd33682)),
  'meta-keyword':
      TextStyle(color: Color(0xffd33682), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffd33682)),
};
