// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const synthMidnightTerminalDarkTheme = {
  'root':
      TextStyle(color: Color(0xffc1c3c4), backgroundColor: Color(0xff050608)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff28292a), color: Color(0xffc1c3c4)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff28292a), color: Color(0xffc1c3c4)),
  'comment': TextStyle(color: Color(0xff474849)),
  'tag': TextStyle(color: Color(0xffa3a5a6)),
  'subst': TextStyle(color: Color(0xffc1c3c4)),
  'punctuation': TextStyle(color: Color(0xffc1c3c4)),
  'operator': TextStyle(color: Color(0xffc1c3c4)),
  'bullet': TextStyle(color: Color(0xffb53b50)),
  'variable': TextStyle(color: Color(0xffb53b50)),
  'template-variable': TextStyle(color: Color(0xffb53b50)),
  'selector-tag': TextStyle(color: Color(0xffb53b50)),
  'name': TextStyle(color: Color(0xffb53b50)),
  'deletion': TextStyle(color: Color(0xffb53b50)),
  'symbol': TextStyle(color: Color(0xffea770d)),
  'number': TextStyle(color: Color(0xffea770d)),
  'link': TextStyle(color: Color(0xffea770d)),
  'attr': TextStyle(color: Color(0xffea770d)),
  'variable.constant_': TextStyle(color: Color(0xffea770d)),
  'literal': TextStyle(color: Color(0xffea770d)),
  'title': TextStyle(color: Color(0xffc9d364)),
  'class-title': TextStyle(color: Color(0xffc9d364)),
  'title.class_': TextStyle(color: Color(0xffc9d364)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffc9d364)),
  'code': TextStyle(color: Color(0xff06ea61)),
  'addition': TextStyle(color: Color(0xff06ea61)),
  'title.class_.inherited__': TextStyle(color: Color(0xff06ea61)),
  'string': TextStyle(color: Color(0xff06ea61)),
  'built_in': TextStyle(color: Color(0xff42fff9)),
  'doctag': TextStyle(color: Color(0xff42fff9)),
  'quote': TextStyle(color: Color(0xff42fff9)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff42fff9)),
  'regexp': TextStyle(color: Color(0xff42fff9)),
  'function-title': TextStyle(color: Color(0xff03aeff)),
  'attribute': TextStyle(color: Color(0xff03aeff)),
  '.ruby-property': TextStyle(color: Color(0xff03aeff)),
  'title.function_': TextStyle(color: Color(0xff03aeff)),
  'section': TextStyle(color: Color(0xff03aeff)),
  'type': TextStyle(color: Color(0xffea5ce2)),
  'template-tag': TextStyle(color: Color(0xffea5ce2)),
  '.diff-meta': TextStyle(color: Color(0xffea5ce2)),
  'keyword': TextStyle(color: Color(0xffea5ce2)),
  'emphasis': TextStyle(color: Color(0xffea5ce2), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffcd6320)),
  'meta-keyword':
      TextStyle(color: Color(0xffcd6320), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffcd6320)),
};
