// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const twilightTheme = {
  'root':
      TextStyle(color: Color(0xffa7a7a7), backgroundColor: Color(0xff1e1e1e)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff464b50), color: Color(0xffa7a7a7)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff464b50), color: Color(0xffa7a7a7)),
  'comment': TextStyle(color: Color(0xff5f5a60)),
  'tag': TextStyle(color: Color(0xff838184)),
  'subst': TextStyle(color: Color(0xffa7a7a7)),
  'punctuation': TextStyle(color: Color(0xffa7a7a7)),
  'operator': TextStyle(color: Color(0xffa7a7a7)),
  'bullet': TextStyle(color: Color(0xffcf6a4c)),
  'variable': TextStyle(color: Color(0xffcf6a4c)),
  'template-variable': TextStyle(color: Color(0xffcf6a4c)),
  'selector-tag': TextStyle(color: Color(0xffcf6a4c)),
  'name': TextStyle(color: Color(0xffcf6a4c)),
  'deletion': TextStyle(color: Color(0xffcf6a4c)),
  'symbol': TextStyle(color: Color(0xffcda869)),
  'number': TextStyle(color: Color(0xffcda869)),
  'link': TextStyle(color: Color(0xffcda869)),
  'attr': TextStyle(color: Color(0xffcda869)),
  'variable.constant_': TextStyle(color: Color(0xffcda869)),
  'literal': TextStyle(color: Color(0xffcda869)),
  'title': TextStyle(color: Color(0xfff9ee98)),
  'class-title': TextStyle(color: Color(0xfff9ee98)),
  'title.class_': TextStyle(color: Color(0xfff9ee98)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xfff9ee98)),
  'code': TextStyle(color: Color(0xff8f9d6a)),
  'addition': TextStyle(color: Color(0xff8f9d6a)),
  'title.class_.inherited__': TextStyle(color: Color(0xff8f9d6a)),
  'string': TextStyle(color: Color(0xff8f9d6a)),
  'built_in': TextStyle(color: Color(0xffafc4db)),
  'doctag': TextStyle(color: Color(0xffafc4db)),
  'quote': TextStyle(color: Color(0xffafc4db)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xffafc4db)),
  'regexp': TextStyle(color: Color(0xffafc4db)),
  'function-title': TextStyle(color: Color(0xff7587a6)),
  'attribute': TextStyle(color: Color(0xff7587a6)),
  '.ruby-property': TextStyle(color: Color(0xff7587a6)),
  'title.function_': TextStyle(color: Color(0xff7587a6)),
  'section': TextStyle(color: Color(0xff7587a6)),
  'type': TextStyle(color: Color(0xff9b859d)),
  'template-tag': TextStyle(color: Color(0xff9b859d)),
  '.diff-meta': TextStyle(color: Color(0xff9b859d)),
  'keyword': TextStyle(color: Color(0xff9b859d)),
  'emphasis': TextStyle(color: Color(0xff9b859d), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff9b703f)),
  'meta-keyword':
      TextStyle(color: Color(0xff9b703f), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xff9b703f)),
};
