// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const unikittyDarkTheme = {
  'root':
      TextStyle(color: Color(0xffbcbabe), backgroundColor: Color(0xff2e2a31)),
  '.hljs::selection':
      TextStyle(backgroundColor: Color(0xff666369), color: Color(0xffbcbabe)),
  '.hljs-::selection':
      TextStyle(backgroundColor: Color(0xff666369), color: Color(0xffbcbabe)),
  'comment': TextStyle(color: Color(0xff838085)),
  'tag': TextStyle(color: Color(0xff9f9da2)),
  'subst': TextStyle(color: Color(0xffbcbabe)),
  'punctuation': TextStyle(color: Color(0xffbcbabe)),
  'operator': TextStyle(color: Color(0xffbcbabe)),
  'bullet': TextStyle(color: Color(0xffd8137f)),
  'variable': TextStyle(color: Color(0xffd8137f)),
  'template-variable': TextStyle(color: Color(0xffd8137f)),
  'selector-tag': TextStyle(color: Color(0xffd8137f)),
  'name': TextStyle(color: Color(0xffd8137f)),
  'deletion': TextStyle(color: Color(0xffd8137f)),
  'symbol': TextStyle(color: Color(0xffd65407)),
  'number': TextStyle(color: Color(0xffd65407)),
  'link': TextStyle(color: Color(0xffd65407)),
  'attr': TextStyle(color: Color(0xffd65407)),
  'variable.constant_': TextStyle(color: Color(0xffd65407)),
  'literal': TextStyle(color: Color(0xffd65407)),
  'title': TextStyle(color: Color(0xffdc8a0e)),
  'class-title': TextStyle(color: Color(0xffdc8a0e)),
  'title.class_': TextStyle(color: Color(0xffdc8a0e)),
  'strong': TextStyle(fontWeight: FontWeight.bold, color: Color(0xffdc8a0e)),
  'code': TextStyle(color: Color(0xff17ad98)),
  'addition': TextStyle(color: Color(0xff17ad98)),
  'title.class_.inherited__': TextStyle(color: Color(0xff17ad98)),
  'string': TextStyle(color: Color(0xff17ad98)),
  'built_in': TextStyle(color: Color(0xff149bda)),
  'doctag': TextStyle(color: Color(0xff149bda)),
  'quote': TextStyle(color: Color(0xff149bda)),
  'keyword.hljs-atrule': TextStyle(color: Color(0xff149bda)),
  'regexp': TextStyle(color: Color(0xff149bda)),
  'function-title': TextStyle(color: Color(0xff796af5)),
  'attribute': TextStyle(color: Color(0xff796af5)),
  '.ruby-property': TextStyle(color: Color(0xff796af5)),
  'title.function_': TextStyle(color: Color(0xff796af5)),
  'section': TextStyle(color: Color(0xff796af5)),
  'type': TextStyle(color: Color(0xffbb60ea)),
  'template-tag': TextStyle(color: Color(0xffbb60ea)),
  '.diff-meta': TextStyle(color: Color(0xffbb60ea)),
  'keyword': TextStyle(color: Color(0xffbb60ea)),
  'emphasis': TextStyle(color: Color(0xffbb60ea), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xffc720ca)),
  'meta-keyword':
      TextStyle(color: Color(0xffc720ca), fontWeight: FontWeight.bold),
  'meta-string': TextStyle(color: Color(0xffc720ca)),
};
